"use client";
import { FormEvent, useEffect, useState } from "react";
import { apiRequest } from "@/lib/api/client";
type Tab = "users" | "drivers" | "races";
type User = { id:number; name:string; email:string; profile:string; status:string; must_change_password:boolean };
type Driver = { id:number; name:string; team:string; status:string; number:number };
type Race = { id:number; name:string; date:string; time:string; type:string; race_status:string; circuit_id?:string };
export function AdminCatalogView() {
 const [tab,setTab]=useState<Tab>("users"); const [items,setItems]=useState<(User|Driver|Race)[]>([]); const [error,setError]=useState(""); const [season,setSeason]=useState(String(new Date().getFullYear())); const [form,setForm]=useState<Record<string,string>>({});
 const load=()=>{const path=tab==="users"?"/api/v1/admin/users":tab==="drivers"?"/api/v1/admin/drivers":`/api/v1/admin/races?season=${season}`; apiRequest<(User|Driver|Race)[]>(path).then(setItems).catch(()=>setError("Acesso restrito ao perfil autorizado ou serviço indisponível."));}; useEffect(load,[tab,season]);
 const set=(key:string,value:string)=>setForm(v=>({...v,[key]:value}));
 async function submit(e:FormEvent){e.preventDefault();setError("");try{if(tab==="users") await apiRequest("/api/v1/admin/users",{method:"POST",body:JSON.stringify({name:form.name,email:form.email,password:form.password,profile:form.profile||"participante",user_status:"ativo"})}); else if(tab==="drivers") await apiRequest("/api/v1/admin/drivers",{method:"POST",body:JSON.stringify({name:form.name,team:form.team||"",status:"Ativo",number:Number(form.number||0)})}); else await apiRequest(`/api/v1/admin/races?season=${season}`,{method:"POST",body:JSON.stringify({name:form.name,date:form.date,time:form.time||"",type:"Normal",race_status:"Pendente",circuit_id:form.circuit_id||null})});setForm({});load();}catch{setError("Não foi possível salvar o registro.");}}
 return <div className="admin-catalog-view"><header className="institutional-hero"><div><p className="eyebrow">Administração</p><h1>Cadastros do campeonato.</h1><p>Gerencie usuários, pilotos e provas com os contratos protegidos da API V4.</p></div></header>
 <div className="admin-tabs" role="tablist">{([["users","Usuários"],["drivers","Pilotos"],["races","Provas"]] as const).map(([key,label])=><button key={key} role="tab" aria-selected={tab===key} className={tab===key?"admin-tab admin-tab--active":"admin-tab"} onClick={()=>{setTab(key);setItems([]);setError("")}}>{label}</button>)}{tab==="races"?<label className="admin-season">Temporada<input value={season} pattern="[0-9]{4}" onChange={e=>setSeason(e.target.value)}/></label>:null}</div>
 {error?<div className="calendar-state calendar-state--error" role="alert">{error}</div>:null}<section className="panel admin-form"><div className="panel__heading"><div><p className="eyebrow">Novo cadastro</p><h2>{tab==="users"?"Convidar usuário":tab==="drivers"?"Adicionar piloto":"Adicionar prova"}</h2></div></div><form className="admin-fields" onSubmit={submit}><label>Nome<input required value={form.name||""} onChange={e=>set("name",e.target.value)}/></label>{tab==="users"?<><label>Email<input required type="email" value={form.email||""} onChange={e=>set("email",e.target.value)}/></label><label>Senha inicial<input required minLength={8} type="password" value={form.password||""} onChange={e=>set("password",e.target.value)}/></label><label>Perfil<select value={form.profile||"participante"} onChange={e=>set("profile",e.target.value)}><option>participante</option><option>admin</option><option>master</option></select></label></>:tab==="drivers"?<><label>Equipe<input value={form.team||""} onChange={e=>set("team",e.target.value)}/></label><label>Número<input type="number" min="0" max="99" value={form.number||""} onChange={e=>set("number",e.target.value)}/></label></>:<><label>Data<input required type="date" value={form.date||""} onChange={e=>set("date",e.target.value)}/></label><label>Horário<input type="time" value={form.time||""} onChange={e=>set("time",e.target.value)}/></label><label>Circuito<input value={form.circuit_id||""} onChange={e=>set("circuit_id",e.target.value)}/></label></>}<button className="primary-action" type="submit">Salvar</button></form></section>
 <section className="panel admin-list"><div className="panel__heading"><h2>Registros</h2><small>{items.length} itens</small></div><div className="table-scroll"><table><thead><tr>{tab==="users"?<><th>Nome</th><th>Email</th><th>Perfil</th><th>Status</th></>:tab==="drivers"?<><th>Nome</th><th>Equipe</th><th>Número</th><th>Status</th></>:<><th>Prova</th><th>Data</th><th>Horário</th><th>Status</th></>}</tr></thead><tbody>{items.map((raw)=><tr key={raw.id}>{tab==="users"?<><td>{(raw as User).name}</td><td>{(raw as User).email}</td><td>{(raw as User).profile}</td><td>{(raw as User).status}</td></>:tab==="drivers"?<><td>{(raw as Driver).name}</td><td>{(raw as Driver).team}</td><td>{(raw as Driver).number}</td><td>{(raw as Driver).status}</td>:<><td>{(raw as Race).name}</td><td>{(raw as Race).date}</td><td>{(raw as Race).time}</td><td>{(raw as Race).race_status}</td></>}</tr>)}</tbody></table></div></section></div>;
}
