import { AccessibleChart } from "./accessible-chart";
import { CalendarIcon, FlagIcon, TrophyIcon } from "./icons";
import { getTeamMarkerBackground, type TeamName } from "@/lib/team-colors";

const ranking: Array<{ position: number; initials: string; name: string; team: TeamName; points: number; delta: string; current?: boolean }> = [
  { position: 1, initials: "AM", name: "Ana Martins", team: "Ferrari", points: 486, delta: "+24" },
  { position: 2, initials: "RC", name: "Rafael Costa", team: "McLaren", points: 471, delta: "+18" },
  { position: 3, initials: "MS", name: "Marcos Silva", team: "Mercedes", points: 458, delta: "+31", current: true },
];

export function DashboardOverview() {
  return <div className="dashboard">
    <header className="page-header"><div><p className="eyebrow">Telemetria · Olá, Marcos</p><h1>A corrida começa antes da largada.</h1><p>Acompanhe sua estratégia para o GP do Azerbaijão.</p></div><button className="season-select" type="button" aria-label="Temporada selecionada: 2026"><span>Temporada</span><strong>2026</strong><span aria-hidden="true">⌄</span></button></header>
    <section className="race-hero" id="calendario" aria-labelledby="next-race-title"><div className="race-hero__glow" aria-hidden="true" /><div className="race-hero__content"><p className="eyebrow"><span className="live-dot" /> Próxima prova · Rodada 7</p><h2 id="next-race-title">GP do Azerbaijão</h2><div className="race-meta"><span><CalendarIcon /> 20 set · 08:00</span><span><FlagIcon /> Baku City Circuit</span></div><div className="countdown" aria-label="Faltam 4 dias, 12 horas e 36 minutos"><span><strong>04</strong><small>dias</small></span><i>:</i><span><strong>12</strong><small>horas</small></span><i>:</i><span><strong>36</strong><small>min</small></span></div><a className="primary-action" href="#apostar">Fazer minha aposta <span aria-hidden="true">→</span></a></div><div className="track-art" aria-hidden="true"><span className="track-art__line">BF1</span><small>BAKU · AZERBAIJÃO</small></div></section>
    <section className="metric-grid" aria-label="Resumo da temporada"><article className="metric-card"><span className="metric-icon"><TrophyIcon /></span><p>Sua posição</p><strong>3º</strong><small><b>↑ 2</b> desde a última prova</small></article><article className="metric-card"><span className="metric-icon"><FlagIcon /></span><p>Pontuação válida</p><strong>458</strong><small>31 pontos na última prova</small></article><article className="metric-card"><span className="metric-icon"><CalendarIcon /></span><p>Apostas enviadas</p><strong>6/6</strong><small><b>100%</b> de participação</small></article></section>
    <div className="content-grid"><AccessibleChart /><section className="panel ranking-panel" id="classificacao" aria-labelledby="ranking-title"><div className="panel__heading"><div><p className="eyebrow">Campeonato</p><h2 id="ranking-title">Classificação</h2></div><a className="text-link" href="#classificacao-completa">Ver todos</a></div><ol className="ranking-list">{ranking.map((person) => <li key={person.position} className={person.current ? "ranking-row ranking-row--current" : "ranking-row"}><strong className="position">{person.position}</strong><span className="avatar avatar--small">{person.initials}</span><span className="driver"><strong className="driver__name"><i className="team-marker" style={{ background: getTeamMarkerBackground(person.team) }} aria-label={`Equipe ${person.team}`} title={person.team} />{person.name}</strong><small>{person.current ? "Você" : `+${486 - person.points} do líder`}</small></span><span className="points"><strong>{person.points}</strong><small>{person.delta}</small></span></li>)}</ol></section></div>
    <footer className="prototype-note"><span>BF1 4.0</span><p>Fundação visual · dados demonstrativos para validação do design system</p></footer>
  </div>;
}
