"use client";
import dynamic from "next/dynamic";
import { useEffect, useMemo, useState } from "react";
import type { ApexOptions } from "apexcharts";
import { apiRequest } from "@/lib/api/client";
import { ParticipantTabs } from "./participant-tabs";
const ApexChart=dynamic(()=>import("react-apexcharts"),{ssr:false,loading:()=> <div className="chart-skeleton"/>});
type Snapshot={entries:{season:string;position:number;points:number}[];seasons_count:number;best_position:number|null;titles:number;podiums:number;best_points:number|null;series:{season:string;drivers:Record<string,number>}[]};
export function PersonalHistoryView(){const[data,setData]=useState<Snapshot|null>(null),[error,setError]=useState(false);useEffect(()=>{apiRequest<Snapshot>("/api/v1/telemetry/history").then(setData).catch(()=>setError(true))},[]);const drivers=useMemo(()=>Array.from(new Set(data?.series.flatMap(s=>Object.keys(s.drivers))??[])).sort(),[data]);const options:ApexOptions={chart:{stacked:true,toolbar:{show:false},foreColor:"#8A94A6"},dataLabels:{enabled:false},grid:{borderColor:"rgba(255,255,255,.08)"},xaxis:{categories:data?.series.map(s=>s.season)??[]},legend:{position:"bottom"}};return <div className="dashboard participant-area"><header className="page-header"><div><p className="eyebrow">Telemetria</p><h1>Histórico.</h1><p>Resultados do Hall da Fama e suas escolhas ao longo das temporadas.</p></div></header><ParticipantTabs />{error?<div className="calendar-state calendar-state--error">Não foi possível carregar seu histórico.</div>:null}{data?<><section className="history-metrics"><HistoryMetric label="Temporadas" value={data.seasons_count} help="Temporadas suas registradas no Hall da Fama."/><HistoryMetric label="Melhor posição" value={data.best_position?`${data.best_position}º`:"—"} help="Sua melhor colocação final registrada."/><HistoryMetric label="Títulos" value={data.titles} help="Quantidade de temporadas encerradas em primeiro lugar."/><HistoryMetric label="Pódios" value={data.podiums} help="Temporadas encerradas entre os três primeiros."/><HistoryMetric label="Maior pontuação" value={data.best_points?.toLocaleString("pt-BR",{maximumFractionDigits:2})??"—"} help="Maior pontuação final registrada no Hall da Fama."/></section><section className="panel"><div className="panel__heading"><div><p className="eyebrow">Temporadas cadastradas</p><h2>Apostas em pilotos por temporada</h2></div></div>{data.series.length?<ApexChart options={options} series={drivers.map(driver=>({name:driver,data:data.series.map(s=>s.drivers[driver]??0)}))} type="bar" height={390}/>:<p className="panel-empty">Ainda não há dados históricos para o gráfico.</p>}</section></>:!error?<div className="calendar-state">Carregando histórico…</div>:null}</div>}
function HistoryMetric({label,value,help}:{label:string;value:string|number;help:string}){return <article className="metric-card history-metric"><button type="button" className="metric-help" title={help} aria-label={`${label}: ${help}`}>?</button><p>{label}</p><strong>{value}</strong><small>{help}</small></article>}
