"""Casos de uso administrativos com autorizacao obrigatoria no servico."""

from __future__ import annotations

from typing import Iterable

from db.db_schema import db_connect, get_table_columns
from db.repo_races import add_piloto, add_prova, delete_piloto, delete_prova, update_piloto, update_prova
from db.repo_users import delete_usuario, update_usuario
from services.access_control import require_operation
from utils.cache_utils import clear_data_cache


def master_ensure_financial_schema() -> None:
    require_operation("usuario.write")
    with db_connect() as conn:
        cursor = conn.cursor()
        cursor.execute("""CREATE TABLE IF NOT EXISTS financeiro_participantes (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, usuario_id INTEGER NOT NULL REFERENCES usuarios(id), temporada TEXT NOT NULL, pago INTEGER NOT NULL DEFAULT 0, atualizado_em TEXT DEFAULT CURRENT_TIMESTAMP, UNIQUE(usuario_id,temporada))""")
        cursor.execute("""CREATE TABLE IF NOT EXISTS financeiro_config_temporada (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, temporada TEXT NOT NULL UNIQUE, valor_taxa REAL NOT NULL DEFAULT 0, atualizado_em TEXT DEFAULT CURRENT_TIMESTAMP)""")
        conn.commit()


def master_create_usuario(nome: str, email: str, senha: str, perfil: str, status: str) -> bool:
    require_operation("usuario.write")
    from services.auth_service import cadastrar_usuario
    return cadastrar_usuario(nome, email, senha, perfil=perfil, status=status)


def master_update_password(user_id: int, password_hash: str) -> bool:
    require_operation("usuario.write")
    from services.data_access_auth import update_user_password
    return update_user_password(int(user_id), password_hash, must_change_password=True)


def master_record_user_status(user_id: int, status: str, *, data_referencia: str | None = None) -> None:
    context = require_operation("usuario.write")
    from services.data_access_auth import registrar_historico_status_usuario
    registrar_historico_status_usuario(int(user_id), status, alterado_por=context.user_id, motivo="gestao_usuarios", data_referencia=data_referencia)


def admin_add_piloto(nome: str, numero: int, equipe: str, status: str) -> bool:
    require_operation("piloto.write")
    return add_piloto(nome, equipe=equipe, status=status, numero=numero)


def admin_update_piloto(piloto_id: int, **campos) -> bool:
    require_operation("piloto.write")
    return update_piloto(piloto_id, **campos)


def admin_delete_piloto(piloto_id: int) -> bool:
    require_operation("piloto.write")
    return delete_piloto(piloto_id)


def admin_add_prova(*, nome: str, data: str, horario_prova: str, status: str, tipo: str, temporada: str, circuit_id: str | None = None) -> bool:
    require_operation("prova.write", season=temporada)
    with db_connect() as conn:
        cursor = conn.cursor()
        cursor.execute("SELECT 1 FROM provas WHERE nome=%s AND data=%s AND temporada=%s LIMIT 1", (nome, data, temporada))
        if cursor.fetchone() is not None:
            return False
    return add_prova(nome, data, horario_prova, tipo, status, temporada, circuit_id=circuit_id)


def admin_update_prova(prova_id: int, *, temporada: str, **campos) -> bool:
    require_operation("prova.write", season=temporada)
    with db_connect() as conn:
        if "circuit_id" not in get_table_columns(conn, "provas"):
            campos.pop("circuit_id", None)
    campos["temporada"] = temporada
    return update_prova(prova_id, **campos)


def admin_delete_prova(prova_id: int, temporada: str) -> bool:
    require_operation("prova.write", season=temporada)
    return delete_prova(prova_id)


def admin_save_resultado(prova_id: int, temporada: str, posicoes: dict, abandonos: list[str]) -> None:
    require_operation("resultado.write", season=temporada)
    with db_connect() as conn:
        cols = get_table_columns(conn, "resultados")
        fields = ["prova_id", "posicoes"]
        values: list[object] = [int(prova_id), str(posicoes)]
        updates = ["posicoes = EXCLUDED.posicoes"]
        if "abandono_pilotos" in cols:
            fields.append("abandono_pilotos"); values.append(",".join(abandonos)); updates.append("abandono_pilotos = EXCLUDED.abandono_pilotos")
        if "temporada" in cols:
            fields.append("temporada"); values.append(str(temporada)); updates.append("temporada = EXCLUDED.temporada")
        placeholders = ", ".join(["%s"] * len(fields))
        conn.cursor().execute(f"INSERT INTO resultados ({', '.join(fields)}) VALUES ({placeholders}) ON CONFLICT (prova_id) DO UPDATE SET {', '.join(updates)}", tuple(values))
        conn.commit()
    clear_data_cache()


def master_update_usuario(user_id: int, **campos) -> bool:
    require_operation("usuario.write")
    return update_usuario(int(user_id), **campos)


def master_delete_usuario(user_id: int) -> bool:
    context = require_operation("usuario.write")
    if int(user_id) == context.user_id:
        raise ValueError("O master nao pode excluir a propria conta.")
    return delete_usuario(int(user_id))


def master_save_hall(entries: Iterable[tuple[int, int, float, str]]) -> int:
    require_operation("hall_da_fama.write")
    values = [(int(u), int(p), float(points), str(season)) for u, p, points, season in entries]
    if not values:
        return 0
    with db_connect() as conn:
        conn.cursor().executemany("""INSERT INTO hall_da_fama (usuario_id,posicao_final,pontos,temporada) VALUES (%s,%s,%s,%s) ON CONFLICT (usuario_id,temporada) DO UPDATE SET posicao_final=EXCLUDED.posicao_final,pontos=EXCLUDED.pontos""", values)
        conn.commit()
    clear_data_cache()
    return len(values)


def master_delete_hall(record_id: int) -> None:
    require_operation("hall_da_fama.write")
    with db_connect() as conn:
        conn.cursor().execute("DELETE FROM hall_da_fama WHERE id=%s", (int(record_id),))
        conn.commit()
    clear_data_cache()


def master_save_financial(temporada: str, pagamentos: dict[int, bool]) -> None:
    require_operation("usuario.write", season=temporada)
    with db_connect() as conn:
        conn.cursor().executemany("""INSERT INTO financeiro_participantes (usuario_id,temporada,pago,atualizado_em) VALUES (%s,%s,%s,CURRENT_TIMESTAMP) ON CONFLICT(usuario_id,temporada) DO UPDATE SET pago=EXCLUDED.pago,atualizado_em=CURRENT_TIMESTAMP""", [(int(uid), str(temporada), 1 if paid else 0) for uid, paid in pagamentos.items()])
        conn.commit()


def master_save_fee(temporada: str, valor: float) -> None:
    require_operation("usuario.write", season=temporada)
    with db_connect() as conn:
        conn.cursor().execute("""INSERT INTO financeiro_config_temporada (temporada,valor_taxa,atualizado_em) VALUES (%s,%s,CURRENT_TIMESTAMP) ON CONFLICT(temporada) DO UPDATE SET valor_taxa=EXCLUDED.valor_taxa,atualizado_em=CURRENT_TIMESTAMP""", (str(temporada), float(valor)))
        conn.commit()
