import streamlit as st
import pandas as pd
import sqlite3
import os
import io  # IMPORTANTE: necessário para exportar Excel em memória
import shutil
import re  # Para conversão de sintaxe SQL
import subprocess
import tempfile
from pathlib import Path
from datetime import datetime
from typing import Any
from urllib.parse import quote_plus
from db.db_utils import db_connect
from db.db_config import DB_BACKEND, DB_PATH, DATABASE_URL  # Importar caminho correto do banco


def _parse_backup_datetime_value(value):
    """Normaliza valores de data/hora de importacao sem acionar warnings do pandas."""
    if pd.isna(value):
        return None

    if isinstance(value, datetime):
        return value.strftime('%Y-%m-%d %H:%M:%S')

    raw = str(value).strip()
    if not raw:
        return None

    formatos_explicitos = (
        '%Y-%m-%dT%H:%M:%S.%f%z',
        '%Y-%m-%dT%H:%M:%S%z',
        '%Y-%m-%d %H:%M:%S',
        '%Y-%m-%d',
        '%d/%m/%Y %H:%M:%S',
        '%d/%m/%Y',
    )
    for formato in formatos_explicitos:
        parsed = pd.to_datetime(raw, format=formato, errors='coerce')
        if pd.notna(parsed):
            return parsed.strftime('%Y-%m-%d %H:%M:%S')

    usa_dayfirst = bool(re.match(r'^\d{1,2}[-/]\d{1,2}[-/]\d{4}(?:\s+\d{1,2}:\d{2}(?::\d{2})?)?$', raw))
    parsed = pd.to_datetime(raw, errors='coerce', dayfirst=usa_dayfirst)
    if pd.notna(parsed):
        return parsed.strftime('%Y-%m-%d %H:%M:%S')
    return None


def _require_master_access():
    perfil = st.session_state.get("user_role", "participante")
    if perfil != "master":
        st.warning("Acesso restrito ao usuário master.")
        st.stop()


def _is_postgres_backend() -> bool:
    return DB_BACKEND == "postgres"


def _sanitize_identifier(identifier: str) -> str:
    value = (identifier or "").strip()
    if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", value):
        raise ValueError(f"Identificador inválido: {identifier}")
    return value


def _quote_identifier(identifier: str) -> str:
    return f'"{_sanitize_identifier(identifier)}"'


def _convert_sqlite_ddl_to_postgres(create_sql: str) -> str:
    ddl = create_sql
    ddl = re.sub(
        r"INTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT",
        "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        ddl,
        flags=re.IGNORECASE,
    )
    ddl = re.sub(r"DEFAULT\s*\(datetime\('now'\)\)", "DEFAULT CURRENT_TIMESTAMP", ddl, flags=re.IGNORECASE)
    ddl = ddl.replace("`", '"')
    return ddl


def _build_pg_uri_for_cli() -> str:
    if DATABASE_URL:
        return DATABASE_URL

    host = os.environ.get("PGHOST", "").strip()
    port = os.environ.get("PGPORT", "5432").strip()
    dbname = os.environ.get("PGDATABASE", "").strip()
    user = os.environ.get("PGUSER", "").strip()
    password = os.environ.get("PGPASSWORD", "").strip()

    if not host or not dbname or not user:
        raise RuntimeError("DATABASE_URL não configurada e variáveis PG* incompletas")

    pwd = quote_plus(password)
    return f"postgresql://{user}:{pwd}@{host}:{port}/{dbname}?sslmode=require"


def _run_pg_client_command(args: list[str], env_overrides: dict[str, str] | None = None) -> tuple[bool, str]:
    env = os.environ.copy()
    if env_overrides:
        env.update(env_overrides)
    try:
        result = subprocess.run(args, capture_output=True, text=True, env=env, check=False)
    except FileNotFoundError:
        return False, f"Comando não encontrado: {args[0]}. Instale 'postgresql-client' no ambiente."

    if result.returncode != 0:
        stderr = (result.stderr or "").strip()
        stdout = (result.stdout or "").strip()
        details = stderr or stdout or "erro desconhecido"
        return False, details
    return True, ""


def get_postgres_backup_mode() -> tuple[str, str]:
    """Detecta modo de backup disponível para PostgreSQL.

    Returns:
        tuple[str, str]:
            - mode: "full" quando pg_dump completo está disponível
                    "fallback" quando somente data-only interno deve ser usado
            - detail: detalhe técnico resumido para exibir na UI
    """
    if not _is_postgres_backend():
        return "sqlite", ""

    try:
        db_uri = _build_pg_uri_for_cli()
        with tempfile.NamedTemporaryFile(prefix="bf1_pg_probe_", suffix=".sql", delete=False) as tmp:
            probe_path = Path(tmp.name)

        ok, error = _run_pg_client_command(
            [
                "pg_dump",
                "--dbname",
                db_uri,
                "--schema-only",
                "--no-owner",
                "--no-privileges",
                "--file",
                str(probe_path),
            ]
        )

        if probe_path.exists():
            probe_path.unlink(missing_ok=True)

        if ok:
            return "full", "Compatível com pg_dump local"

        if "server version mismatch" in error.lower():
            return "fallback", "Incompatibilidade de versão do pg_dump"

        if "comando não encontrado" in error.lower():
            return "fallback", "pg_dump não encontrado no ambiente"

        return "fallback", "pg_dump indisponível para backup completo"

    except Exception as exc:
        return "fallback", f"Falha ao validar pg_dump: {exc}"


def _sql_literal(value: Any) -> str:
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "TRUE" if value else "FALSE"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, bytes):
        return "'\\x" + value.hex() + "'::bytea"
    text = str(value).replace("'", "''")
    return f"'{text}'"


def _drop_all_tables_current_schema(cursor: Any) -> None:
    cursor.execute(
        """
        SELECT table_name
        FROM information_schema.tables
        WHERE table_schema = current_schema()
          AND table_type = 'BASE TABLE'
        ORDER BY table_name
        """
    )
    table_rows = cursor.fetchall() or []
    table_names = [str(r[0]) for r in table_rows if r and r[0]]
    for table_name in table_names:
        cursor.execute(f"DROP TABLE IF EXISTS {_quote_identifier(table_name)} CASCADE")


def _generate_postgres_data_only_dump() -> bytes:
    """Gera dump SQL data-only para fallback quando pg_dump não é compatível."""
    lines: list[str] = []
    ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    lines.append("-- BF1 POSTGRES DATA-ONLY DUMP")
    lines.append(f"-- gerado em {ts}")

    with db_connect() as conn:
        cursor = conn.cursor()
        cursor.execute(
            """
            SELECT table_name
            FROM information_schema.tables
            WHERE table_schema = current_schema()
              AND table_type = 'BASE TABLE'
            ORDER BY table_name
            """
        )
        table_rows = cursor.fetchall() or []
        table_names = [str(r[0]) for r in table_rows if r and r[0]]

        lines.append("BEGIN;")
        if table_names:
            quoted_tables = ", ".join(_quote_identifier(t) for t in table_names)
            lines.append(f"TRUNCATE TABLE {quoted_tables} RESTART IDENTITY CASCADE;")

        for table_name in table_names:
            cursor.execute(f"PRAGMA table_info('{table_name}')")
            cols_info = cursor.fetchall() or []
            cols = [str(c[1]) for c in cols_info]
            if not cols:
                continue
            cols_sql = ", ".join(_quote_identifier(c) for c in cols)

            cursor.execute(f"SELECT * FROM {_quote_identifier(table_name)}")
            rows = cursor.fetchall() or []
            for row in rows:
                values_sql = ", ".join(_sql_literal(row[i]) for i in range(len(cols)))
                lines.append(
                    f"INSERT INTO {_quote_identifier(table_name)} ({cols_sql}) VALUES ({values_sql});"
                )

        lines.append("COMMIT;")

    return ("\n".join(lines) + "\n").encode("utf-8")


def _overwrite_postgres_from_sql_file(sql_file: Path) -> tuple[bool, str]:
    db_uri = _build_pg_uri_for_cli()

    try:
        sql_head = sql_file.read_text(encoding="utf-8", errors="ignore")[:4096]
    except Exception:
        sql_head = ""

    is_data_only_dump = "BF1 POSTGRES DATA-ONLY DUMP" in sql_head

    if is_data_only_dump:
        try:
            sql_content = sql_file.read_text(encoding="utf-8", errors="ignore")
            with db_connect() as conn:
                cursor = conn.cursor()
                statements = [s.strip() for s in sql_content.split(";") if s.strip()]
                for statement in statements:
                    cursor.execute(statement)
                conn.commit()
            return True, ""
        except Exception as exc:
            return False, f"Falha ao aplicar dump data-only: {exc}"

    # Para dumps completos, limpar tabelas do schema atual sem depender de ownership do schema.
    try:
        with db_connect() as conn:
            cursor = conn.cursor()
            _drop_all_tables_current_schema(cursor)
            conn.commit()
    except Exception as exc:
        return False, f"Falha ao limpar tabelas atuais: {exc}"

    ok, error = _run_pg_client_command(
        [
            "psql",
            "--dbname",
            db_uri,
            "--set",
            "ON_ERROR_STOP=on",
            "--single-transaction",
            "--file",
            str(sql_file),
        ]
    )
    if not ok:
        return False, f"Falha ao restaurar dump: {error}"
    return True, ""


def _migrate_sqlite_file_to_postgres(sqlite_file: Path) -> tuple[bool, str, dict[str, int]]:
    stats = {"tables": 0, "rows": 0}
    if not sqlite_file.exists():
        return False, "Arquivo .db não encontrado", stats

    source = sqlite3.connect(str(sqlite_file))
    source.row_factory = sqlite3.Row
    target_ctx = db_connect()

    try:
        with target_ctx as target:
            cursor_t = target.cursor()
            _drop_all_tables_current_schema(cursor_t)

            cursor_s = source.cursor()
            cursor_s.execute(
                "SELECT name, sql FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name"
            )
            tables = cursor_s.fetchall()

            for table in tables:
                table_name = _sanitize_identifier(table[0])
                create_sql = table[1]
                if not create_sql:
                    continue

                ddl = _convert_sqlite_ddl_to_postgres(create_sql)
                cursor_t.execute(ddl)
                stats["tables"] += 1

            for table in tables:
                table_name = _sanitize_identifier(table[0])
                cursor_s.execute(f'SELECT * FROM "{table_name}"')
                rows = cursor_s.fetchall()
                if not rows:
                    continue

                cols = [str(col) for col in rows[0].keys()]
                placeholders = ", ".join(["?"] * len(cols))
                cols_sql = ", ".join(_quote_identifier(col) for col in cols)
                insert_sql = (
                    f"INSERT INTO {_quote_identifier(table_name)} ({cols_sql}) "
                    f"VALUES ({placeholders})"
                )
                values = [tuple(row[col] for col in cols) for row in rows]
                cursor_t.executemany(insert_sql, values)
                stats["rows"] += len(values)

            target.commit()
        return True, "", stats
    except Exception as exc:
        return False, str(exc), stats
    finally:
        source.close()

def download_db():
    """Permite download completo do banco (SQLite .db ou PostgreSQL .sql)."""
    _require_master_access()

    if _is_postgres_backend():
        try:
            st.info("🔄 Gerando dump completo do PostgreSQL...")
            db_uri = _build_pg_uri_for_cli()
            with tempfile.NamedTemporaryFile(prefix="bf1_pg_dump_", suffix=".sql", delete=False) as tmp:
                dump_path = Path(tmp.name)

            ok, error = _run_pg_client_command(
                [
                    "pg_dump",
                    "--dbname",
                    db_uri,
                    "--format=plain",
                    "--no-owner",
                    "--no-privileges",
                    "--inserts",
                    "--file",
                    str(dump_path),
                ]
            )
            if not ok:
                error_lower = error.lower()
                if "server version mismatch" in error_lower:
                    st.warning(
                        "⚠️ Versão do pg_dump incompatível com o servidor. "
                        "Gerando fallback data-only diretamente pela aplicação."
                    )
                    dump_bytes = _generate_postgres_data_only_dump()
                    if dump_path.exists():
                        dump_path.unlink(missing_ok=True)
                    st.download_button(
                        label="⬇️ Baixar backup completo PostgreSQL (.sql)",
                        data=dump_bytes,
                        file_name=f"bolao_f1_pg_backup_{datetime.now().strftime('%Y%m%d_%H%M%S')}.sql",
                        mime="application/sql",
                        width="stretch",
                        help="Dump data-only gerado internamente (sem dependência de versão do pg_dump)",
                    )
                    return
                st.error(f"❌ Erro ao gerar dump PostgreSQL: {error}")
                if dump_path.exists():
                    dump_path.unlink(missing_ok=True)
                return

            dump_bytes = dump_path.read_bytes()
            dump_path.unlink(missing_ok=True)
            st.download_button(
                label="⬇️ Baixar backup completo PostgreSQL (.sql)",
                data=dump_bytes,
                file_name=f"bolao_f1_pg_backup_{datetime.now().strftime('%Y%m%d_%H%M%S')}.sql",
                mime="application/sql",
                width="stretch",
                help="Dump completo do PostgreSQL com INSERTs para restauração no painel",
            )
            return
        except Exception as exc:
            st.error(f"❌ Erro ao preparar backup PostgreSQL: {exc}")
            return

    if DB_PATH.exists():
        try:
            # Consolidar WAL no banco original
            with sqlite3.connect(DB_PATH, timeout=30) as conn:
                conn.execute("PRAGMA wal_checkpoint(TRUNCATE)")
                conn.execute("VACUUM")
            
            # Criar versão limpa via backup API do sqlite3
            temp_dir = tempfile.mkdtemp()
            temp_clean = Path(temp_dir) / "bolao_f1_clean.db"
            
            st.info("🔄 Preparando banco de dados limpo para download...")
            
            # Usar backup API do sqlite3 (mais confiável)
            source = sqlite3.connect(str(DB_PATH), timeout=30)
            dest = sqlite3.connect(str(temp_clean), timeout=30)
            
            with source:
                source.backup(dest)
            
            source.close()
            
            # Otimizar banco destino
            with dest:
                dest.execute("PRAGMA integrity_check")
                dest.execute("VACUUM")
            dest.close()
            
            # Ler arquivo limpo
            with open(temp_clean, "rb") as fp:
                db_data = fp.read()
            
            # Limpar temporário
            shutil.rmtree(temp_dir)
            
            st.download_button(
                label="⬇️ Baixar banco de dados completo (limpo e consolidado)",
                data=db_data,
                file_name=f"bolao_f1_backup_{datetime.now().strftime('%Y%m%d_%H%M%S')}.db",
                mime="application/octet-stream",
                width="stretch",
                help="Banco de dados validado, consolidado e livre de corrupção WAL"
            )
            
        except Exception as e:
            st.error(f"⚠️ Erro ao preparar download: {e}")
            st.info("Tentando download direto (pode conter WAL não consolidado)...")
            # Fallback: download direto
            try:
                with sqlite3.connect(DB_PATH) as conn:
                    conn.execute("PRAGMA wal_checkpoint(TRUNCATE)")
            except:
                pass
            with open(DB_PATH, "rb") as fp:
                db_data = fp.read()
            st.download_button(
                label="⬇️ Baixar banco de dados completo (.db)",
                data=db_data,
                file_name=DB_PATH.name,
                mime="application/octet-stream",
                width="stretch"
            )
    else:
        st.warning(f"⚠️ Arquivo do banco de dados não encontrado: {DB_PATH}")
        st.info(f"📍 Caminho esperado: {DB_PATH.absolute()}")

def upload_db():
    """Permite upload/restauração completa do banco de dados."""
    _require_master_access()

    if _is_postgres_backend():
        st.error("🚨 **ATENÇÃO: SUBSTITUIÇÃO COMPLETA DO BANCO PostgreSQL**")
        st.warning(
            "⚠️ Esta operação irá remover todo o schema atual e restaurar a partir do arquivo .sql informado."
        )

        uploaded_file = st.file_uploader(
            "Faça upload do arquivo .sql de backup completo do PostgreSQL",
            type=["sql"],
            key="upload_whole_db_postgres",
            help="Use preferencialmente arquivo .sql gerado pelo botão de download completo",
        )

        if uploaded_file is None:
            return

        try:
            with tempfile.NamedTemporaryFile(prefix="bf1_pg_restore_", suffix=".sql", delete=False) as tmp:
                tmp.write(uploaded_file.getbuffer())
                sql_file = Path(tmp.name)

            st.info("🔄 Restaurando dump completo no PostgreSQL...")
            ok, error = _overwrite_postgres_from_sql_file(sql_file)
            sql_file.unlink(missing_ok=True)
            if not ok:
                st.error(f"❌ Falha na restauração completa: {error}")
                return

            st.success("✅ Banco PostgreSQL restaurado com sucesso.")
            st.cache_data.clear()
            st.rerun()
        except Exception as exc:
            st.error(f"❌ Erro durante restauração PostgreSQL: {exc}")
        return
    
    # Mostrar mensagem de sucesso se houver importação recente
    if 'import_success' in st.session_state:
        info = st.session_state.import_success
        
        if info.get('type') == 'db':
            st.success("✅ Banco de dados .db validado e restaurado com sucesso!")
        else:
            st.success(f"✅ Importação concluída: {info['tables']} tabelas, {info['records']} registros")
            if info['errors'] > 0:
                st.warning(f"⚠️ {info['errors']} comandos falharam (podem ser erros esperados de sintaxe)")
        st.info(f"📊 Tamanho do banco: {info.get('db_size', 0) / 1024:.1f} KB")
        st.info("💾 Backup do banco anterior salvo em /backups/")
        del st.session_state.import_success
        return  # IMPORTANTE: Sair da função após mostrar sucesso
    
    st.error("🚨 **ATENÇÃO: SUBSTITUIÇÃO COMPLETA DO BANCO**")
    st.warning("⚠️ Esta operação irá **DELETAR E SUBSTITUIR TODO O BANCO DE DADOS**. Um backup automático será criado antes da substituição.")
    
    uploaded_file = st.file_uploader(
        "Faça upload de um arquivo .db (SQLite) ou .sql (dump MySQL/SQLite)",
        type=["db", "sqlite", "sql"],
        key="upload_whole_db",
        help="Arquivos .db: banco SQLite completo | Arquivos .sql: dump SQL (converte MySQL→SQLite automaticamente)"
    )
    
    if uploaded_file is not None:
        
        import re
        
        # Detectar tipo de arquivo
        file_extension = uploaded_file.name.split('.')[-1].lower()
        
        if file_extension == 'sql':
            # ===== IMPORTAÇÃO DE ARQUIVO SQL =====
            st.info("📄 Detectado arquivo SQL - Iniciando conversão e importação...")
            
            # Salvar arquivo SQL temporário
            temp_dir = tempfile.mkdtemp()
            temp_sql = Path(temp_dir) / "uploaded.sql"
            temp_new_db = Path(temp_dir) / "new_database.db"
            
            with open(temp_sql, "wb") as f:
                f.write(uploaded_file.getbuffer())
            
            try:
                # Ler e converter SQL
                with open(temp_sql, 'r', encoding='utf-8') as f:
                    sql_content = f.read()
                
                # Converter sintaxe MySQL para SQLite
                st.info("🔄 Convertendo sintaxe MySQL → SQLite...")
                
                # Remover AUTO_INCREMENT mas marcar onde estava
                sql_content = re.sub(r'`(\w+)`\s+integer\s+AUTO_INCREMENT', r'"\1" INTEGER PRIMARY KEY AUTOINCREMENT', sql_content, flags=re.IGNORECASE)
                sql_content = re.sub(r'(\w+)\s+integer\s+AUTO_INCREMENT', r'\1 INTEGER PRIMARY KEY AUTOINCREMENT', sql_content, flags=re.IGNORECASE)
                
                # Remover PRIMARY KEY separado se já está na coluna
                sql_content = re.sub(r',?\s*PRIMARY KEY\s*\([^)]+\)\s*', '', sql_content, flags=re.IGNORECASE)
                
                # Substituir backticks por aspas duplas
                sql_content = sql_content.replace('`', '"')
                
                # Remover cláusulas MySQL-specific
                sql_content = re.sub(r'\s*ENGINE\s*=\s*\w+', '', sql_content, flags=re.IGNORECASE)
                sql_content = re.sub(r'\s*DEFAULT\s+CHARSET\s*=\s*\w+', '', sql_content, flags=re.IGNORECASE)
                sql_content = re.sub(r'\s*COLLATE\s*=\s*\w+', '', sql_content, flags=re.IGNORECASE)
                
                # Criar novo banco e importar
                st.info("📥 Importando dados para novo banco...")
                conn = sqlite3.connect(str(temp_new_db), timeout=300, isolation_level='DEFERRED')
                cursor = conn.cursor()
                cursor.execute("PRAGMA foreign_keys=OFF")
                cursor.execute("PRAGMA synchronous=FULL")  # CRITICAL: FULL garante persistência
                cursor.execute("PRAGMA journal_mode=WAL")  # WAL para performance mantendo segurança
                cursor.execute("PRAGMA cache_size=10000")  # Cache maior para performance
                cursor.execute("PRAGMA temp_store=MEMORY")  # Usar memória para temp
                
                # Separar em comandos
                statements = []
                current_statement = []
                for line in sql_content.split('\n'):
                    line = line.strip()
                    if not line or line.startswith('--'):
                        continue
                    current_statement.append(line)
                    if line.endswith(';'):
                        statements.append(' '.join(current_statement))
                        current_statement = []
                
                # Executar comandos em lotes
                successful = 0
                failed = 0
                total = len(statements)
                
                progress_bar = st.progress(0)
                status_text = st.empty()
                status_text.text(f"Iniciando importação de {total} comandos...")
                
                cursor.execute("BEGIN")
                last_update = 0
                
                for i, statement in enumerate(statements):
                    try:
                        cursor.execute(statement)
                        successful += 1
                        
                        # Commit a cada 100 comandos para não perder progresso
                        if i > 0 and i % 100 == 0:
                            conn.commit()
                            cursor.execute("BEGIN")
                            
                            # Atualizar UI apenas a cada 100 comandos (não mais frequente)
                            if i - last_update >= 100:
                                progress_bar.progress(min(i / total, 0.99))
                                status_text.text(f"Importando: {i}/{total} comandos ({int(i/total*100)}%)")
                                last_update = i
                            
                    except sqlite3.Error as e:
                        failed += 1
                        if failed <= 3:  # Mostrar apenas os 3 primeiros erros
                            st.warning(f"⚠️ Erro {failed}: {str(e)[:80]}")
                
                conn.commit()  # Commit final
                progress_bar.progress(1.0)
                status_text.text(f"Finalizando importação...")
                
                cursor.execute("PRAGMA foreign_keys=ON")
                
                # CRÍTICO: Consolidar WAL antes de fechar - força todos os dados para o arquivo principal
                cursor.execute("PRAGMA wal_checkpoint(TRUNCATE)")
                cursor.execute("VACUUM")  # Otimizar banco
                conn.commit()
                
                # Verificar dados importados
                cursor.execute("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'")
                tables_imported = cursor.fetchall()
                
                # Contar registros totais
                total_records = 0
                for table in tables_imported:
                    cursor.execute(f"SELECT COUNT(*) FROM \"{table[0]}\"")
                    total_records += cursor.fetchone()[0]
                
                conn.close()
                
                # Limpar elementos de progresso antes das mensagens finais
                progress_bar.empty()
                status_text.empty()
                
                # CRÍTICO: Fechar TODAS as conexões ANTES de substituir arquivo
                from db.connection_pool import close_pool
                try:
                    close_pool()  # Fecha pool e libera locks
                except Exception as e:
                    pass  # Ignorar se pool não existir
                
                # Pequena pausa para garantir que locks foram liberados
                import time
                time.sleep(0.3)
                
                # Criar backup do banco atual usando sqlite3.backup (garante WAL)
                if DB_PATH.exists():
                    backup_path = Path("backups")
                    backup_path.mkdir(exist_ok=True)
                    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
                    backup_file = backup_path / f"backup_antes_sql_import_{timestamp}.db"
                    src = sqlite3.connect(str(DB_PATH), timeout=30)
                    bkp = sqlite3.connect(str(backup_file), timeout=30)
                    try:
                        src.execute("PRAGMA wal_checkpoint(TRUNCATE)")
                        src.backup(bkp)
                    finally:
                        src.close()
                        bkp.close()
                
                # Remover arquivo destino antigo e seus WAL/SHM
                if DB_PATH.exists():
                    DB_PATH.unlink()
                wal_file = Path(str(DB_PATH) + "-wal")
                shm_file = Path(str(DB_PATH) + "-shm")
                if wal_file.exists():
                    wal_file.unlink()
                if shm_file.exists():
                    shm_file.unlink()
                
                # Usar backup API do sqlite3 (mais confiável que shutil.copy2)
                source_conn = sqlite3.connect(str(temp_new_db), timeout=30)
                dest_conn = sqlite3.connect(str(DB_PATH), timeout=30)
                source_conn.backup(dest_conn)
                source_conn.close()
                
                # Consolidar WAL no destino e fechar
                dest_conn.execute("PRAGMA wal_checkpoint(TRUNCATE)")
                dest_conn.execute("VACUUM")
                dest_conn.close()
                
                # Verificar que o arquivo foi copiado corretamente
                if not DB_PATH.exists() or DB_PATH.stat().st_size == 0:
                    raise Exception(f"Erro ao salvar banco: arquivo vazio ou não existe! Path: {DB_PATH}")
                
                # Remover WAL/SHM que podem ter sido criados
                if wal_file.exists():
                    wal_file.unlink()
                if shm_file.exists():
                    shm_file.unlink()
                
                shutil.rmtree(temp_dir)
                
                # Limpar cache e criar mensagem de sucesso
                st.cache_data.clear()
                st.session_state['import_success'] = {
                    'tables': len(tables_imported),
                    'records': total_records,
                    'commands': successful,
                    'errors': failed,
                    'db_size': DB_PATH.stat().st_size
                }
                st.rerun()
                
            except Exception as e:
                st.error(f"❌ Erro ao importar SQL: {e}")
                import traceback
                st.code(traceback.format_exc())
                try:
                    shutil.rmtree(temp_dir)
                except:
                    pass
                return
        
        else:
            # ===== IMPORTAÇÃO DE ARQUIVO .DB =====
            import tempfile
        
            # Salvar arquivo temporário
            temp_dir = tempfile.mkdtemp()
            temp_uploaded = Path(temp_dir) / "uploaded.db"
            temp_clean = Path(temp_dir) / "clean.db"
        
            with open(temp_uploaded, "wb") as f:
                f.write(uploaded_file.getbuffer())
        
            try:
                st.info("🔄 Validando e limpando banco de dados...")
                
                # Verificar integridade e consolidar WAL usando API Python nativa
                source_conn = sqlite3.connect(str(temp_uploaded), timeout=30)
                
                try:
                    result = source_conn.execute("PRAGMA integrity_check").fetchone()
                    if result[0] != "ok":
                        st.error(f"❌ Arquivo de backup está corrompido: {result[0]}")
                        source_conn.close()
                        shutil.rmtree(temp_dir)
                        return
                    
                    # Consolidar WAL
                    source_conn.execute("PRAGMA wal_checkpoint(TRUNCATE)")
                    source_conn.execute("VACUUM")
                    
                    # Criar versão limpa usando backup API
                    dest_conn = sqlite3.connect(str(temp_clean), timeout=30)
                    source_conn.backup(dest_conn)
                    source_conn.close()
                    
                    # Otimizar destino
                    dest_conn.execute("VACUUM")
                    dest_conn.close()
                    
                except sqlite3.DatabaseError as db_error:
                    st.error(f"❌ Erro no banco de dados: {db_error}")
                    try:
                        source_conn.close()
                    except:
                        pass
                    shutil.rmtree(temp_dir)
                    return
                
                # CRÍTICO: Fechar TODAS as conexões ANTES de substituir arquivo
                from db.connection_pool import close_pool
                try:
                    close_pool()  # Fecha pool e libera locks
                except Exception as e:
                    st.warning(f"⚠️ Aviso ao fechar pool: {e}")
                
                # Pequena pausa para garantir que locks foram liberados
                import time
                time.sleep(0.5)
                
                # Criar backup antes de sobrescrever usando sqlite3.backup (garante WAL)
                if DB_PATH.exists():
                    backup_path = Path("backups")
                    backup_path.mkdir(exist_ok=True)
                    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
                    backup_file = backup_path / f"backup_antes_restauracao_{timestamp}.db"
                    src = sqlite3.connect(str(DB_PATH), timeout=30)
                    bkp = sqlite3.connect(str(backup_file), timeout=30)
                    try:
                        src.execute("PRAGMA wal_checkpoint(TRUNCATE)")
                        src.backup(bkp)
                    finally:
                        src.close()
                        bkp.close()
                
                # Sobrescrever banco com versão limpa usando sqlite3.backup (garante WAL)
                st.info(f"📋 Debug: Copiando {temp_clean} → {DB_PATH}")
                st.info(f"📋 Tamanho fonte: {temp_clean.stat().st_size} bytes")
                
                # Usar API de backup do SQLite para garantir integridade
                src_conn = sqlite3.connect(str(temp_clean), timeout=30)
                dst_conn = sqlite3.connect(str(DB_PATH), timeout=30)
                try:
                    src_conn.backup(dst_conn)
                    dst_conn.execute("PRAGMA wal_checkpoint(TRUNCATE)")
                    dst_conn.execute("VACUUM")
                finally:
                    src_conn.close()
                    dst_conn.close()
                
                st.info(f"📋 Tamanho destino: {DB_PATH.stat().st_size} bytes")
                
                # Verificar que o arquivo foi copiado corretamente
                if not DB_PATH.exists() or DB_PATH.stat().st_size == 0:
                    raise Exception(f"Erro ao salvar banco: arquivo vazio ou não existe! Path: {DB_PATH}")
                
                # IMPORTANTE: Remover arquivos WAL/SHM antigos que podem causar problemas
                wal_file = Path(str(DB_PATH) + "-wal")
                shm_file = Path(str(DB_PATH) + "-shm")
                if wal_file.exists():
                    wal_file.unlink()
                if shm_file.exists():
                    shm_file.unlink()
                
                # Limpar temporários
                shutil.rmtree(temp_dir)
                
                # Debug: verificar arquivo DIRETAMENTE (sem pool/cache)
                try:
                    direct_conn = sqlite3.connect(str(DB_PATH))
                    cursor = direct_conn.cursor()
                    cursor.execute("SELECT COUNT(*) FROM usuarios")
                    usuarios_direct = cursor.fetchone()[0]
                    cursor.execute("SELECT COUNT(*) FROM apostas")
                    apostas_direct = cursor.fetchone()[0]
                    direct_conn.close()
                    st.info(f"🔍 Arquivo direto: {usuarios_direct} usuários, {apostas_direct} apostas")
                except Exception as e:
                    st.error(f"❌ Erro ao ler arquivo direto: {e}")

                # Debug: verificar dados PELO POOL (pool será recriado lazily)
                try:
                    with db_connect() as conn:
                        cursor = conn.cursor()
                        cursor.execute("SELECT COUNT(*) FROM usuarios")
                        usuarios_pool = cursor.fetchone()[0]
                        cursor.execute("SELECT COUNT(*) FROM apostas")
                        apostas_pool = cursor.fetchone()[0]
                        st.info(f"🔍 Pelo pool: {usuarios_pool} usuários, {apostas_pool} apostas")
                except Exception as e:
                    st.warning(f"⚠️ Erro ao verificar pelo pool: {e}")

                # Limpar cache e criar mensagem de sucesso
                st.cache_data.clear()
                st.session_state['import_success'] = {
                    'tables': 0,
                    'records': 0,
                    'commands': 0,
                    'errors': 0,
                    'type': 'db',
                    'db_size': DB_PATH.stat().st_size
                }
                st.rerun()
                
            except Exception as e:
                st.error(f"❌ Erro inesperado: {e}")
                import traceback
                st.code(traceback.format_exc())
                try:
                    shutil.rmtree(temp_dir)
                except:
                    pass

def listar_tabelas():
    """Retorna o nome de todas as tabelas do banco de dados."""
    try:
        with db_connect() as conn:
            if _is_postgres_backend():
                query = """
                    SELECT table_name AS name
                    FROM information_schema.tables
                    WHERE table_schema = 'public'
                      AND table_type = 'BASE TABLE'
                    ORDER BY table_name
                """
            else:
                query = "SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'"
            tabelas = pd.read_sql_query(query, conn)["name"].tolist()
        return tabelas
    except Exception as e:
        st.error(f"❌ Erro ao listar tabelas: {e}")
        return []

def exportar_tabela_excel(tabela):
    """Exporta os dados da tabela como arquivo Excel em buffer de memória."""
    table_name = _sanitize_identifier(tabela)
    with db_connect() as conn:
        df = pd.read_sql_query(f"SELECT * FROM {_quote_identifier(table_name)}", conn)
    output = io.BytesIO()
    with pd.ExcelWriter(output, engine='openpyxl') as writer:
        df.to_excel(writer, index=False, sheet_name=table_name)
    output.seek(0)
    return output

def download_tabela():
    """Interface para download de tabela específica."""
    _require_master_access()
    tabelas = listar_tabelas()
    
    if not tabelas:
        st.warning("⚠️ Nenhuma tabela encontrada no banco de dados.")
        return
    
    tabela = st.selectbox("Selecione a tabela para exportar", tabelas, key="select_export")
    
    if st.button("📊 Exportar para Excel", width="stretch", type="primary"):
        try:
            excel_buffer = exportar_tabela_excel(tabela)
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            
            st.download_button(
                label=f"⬇️ Baixar tabela {tabela} (.xlsx)",
                data=excel_buffer,
                file_name=f"{tabela}_{timestamp}.xlsx",
                mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                width="stretch"
            )
            st.success(f"✅ Tabela '{tabela}' exportada com sucesso!")
        except Exception as e:
            st.error(f"❌ Erro ao exportar tabela: {e}")

def upload_tabela():
    """Interface para upload/importação de tabela específica."""
    _require_master_access()
    tabelas = listar_tabelas()
    
    if not tabelas:
        st.warning("⚠️ Nenhuma tabela encontrada no banco de dados.")
        return
    
    tabela = st.selectbox("Escolha a tabela para sobrescrever:", tabelas, key="select_import")
    
    st.error("🚨 **ATENÇÃO: OPERAÇÃO DESTRUTIVA**")
    st.warning("⚠️ Esta operação irá **DELETAR PERMANENTEMENTE TODOS OS DADOS** da tabela selecionada e substituí-los pelo conteúdo do arquivo Excel. Esta ação não pode ser desfeita!")
    
    uploaded_file = st.file_uploader(
        f"Upload do arquivo .xlsx para substituir dados da tabela '{tabela}'",
        type=["xlsx"], 
        key="upload_one_table"
    )
    
    if uploaded_file is not None and tabela:
        try:
            df = pd.read_excel(uploaded_file)
        except Exception as e:
            st.error(f"❌ Não foi possível ler o Excel: {e}")
            return

        st.write(f"👀 Prévia dos dados ({len(df)} linhas):")
        st.dataframe(df.head(10))

        if st.button("✅ Confirmar Importação - SOBRESCREVER TODOS OS DADOS", type="primary", width="stretch"):
            try:
                table_name = _sanitize_identifier(tabela)
                with db_connect() as conn:
                    cursor = conn.cursor()
                    cols_info = cursor.execute(f"PRAGMA table_info('{table_name}')").fetchall()
                    if not cols_info:
                        raise ValueError(f"Tabela '{table_name}' não encontrada no banco.")
                    db_cols = [r[1] for r in cols_info]
                    db_col_types = {r[1]: (r[2] or '').upper() for r in cols_info}

                    missing_cols = [c for c in db_cols if c not in df.columns]
                    extra_cols = [c for c in df.columns if c not in db_cols]
                    if missing_cols:
                        raise ValueError(f"Colunas faltantes no Excel: {missing_cols}")
                    if extra_cols:
                        st.info(f"ℹ️ Colunas extras no Excel serão ignoradas: {extra_cols}")
                    df_alinhado = df[db_cols].copy()

                    for col_name in db_cols:
                        col_type = db_col_types.get(col_name, '')
                        series = df_alinhado[col_name]

                        if "INT" in col_type or "BOOL" in col_type:
                            coerced = pd.to_numeric(series, errors='coerce').astype('Int64')
                            df_alinhado[col_name] = coerced.where(~coerced.isna(), None)
                            continue
                        if any(t in col_type for t in ["REAL", "FLOA", "DOUB", "NUM", "DEC"]):
                            coerced = pd.to_numeric(series, errors='coerce')
                            df_alinhado[col_name] = coerced.where(~coerced.isna(), None)
                            continue
                        if any(t in col_type for t in ["DATE", "TIME"]):
                            df_alinhado[col_name] = series.apply(_parse_backup_datetime_value)
                            continue

                    df_alinhado = df_alinhado.where(pd.notnull(df_alinhado), None)

                    count_before = cursor.execute(
                        f"SELECT COUNT(*) FROM {_quote_identifier(table_name)}"
                    ).fetchone()[0]

                    if _is_postgres_backend():
                        cursor.execute(f"TRUNCATE TABLE {_quote_identifier(table_name)} RESTART IDENTITY CASCADE")
                    else:
                        cursor.execute(f"DELETE FROM {_quote_identifier(table_name)}")

                    count_after_delete = cursor.execute(
                        f"SELECT COUNT(*) FROM {_quote_identifier(table_name)}"
                    ).fetchone()[0]

                    if not df_alinhado.empty:
                        insert_cols = ", ".join(_quote_identifier(col) for col in db_cols)
                        placeholders = ", ".join(["?"] * len(db_cols))
                        insert_sql = (
                            f"INSERT INTO {_quote_identifier(table_name)} ({insert_cols}) "
                            f"VALUES ({placeholders})"
                        )
                        values: list[tuple[Any, ...]] = [
                            tuple(row[col] for col in db_cols)
                            for row in df_alinhado.to_dict("records")
                        ]
                        cursor.executemany(insert_sql, values)

                    conn.commit()

                    count_after_insert = cursor.execute(
                        f"SELECT COUNT(*) FROM {_quote_identifier(table_name)}"
                    ).fetchone()[0]
                
                # CRÍTICO: Fechar pool para forçar recriação após modificar dados
                from db.connection_pool import close_pool
                try:
                    close_pool()  # Fecha pool atual, será recriado automaticamente na próxima consulta
                except Exception as e:
                    st.error(f"❌ Erro ao fechar pool de conexões: {e}")
                    raise

                st.success(f"✅ Tabela '{table_name}' completamente sobrescrita!")
                st.info(f"🗑️ Registros deletados: {count_before}")
                st.info(f"📥 Registros importados: {count_after_insert}")
                st.cache_data.clear()
                st.rerun()
            except Exception as e:
                st.error(f"❌ Erro ao importar tabela: {e}")
                st.info("💡 Verifique se as colunas do arquivo Excel correspondem exatamente às colunas da tabela.")
                import traceback
                st.code(traceback.format_exc())


def migrar_sqlite_para_postgres():
    """Interface para migração de arquivo SQLite (.db) para PostgreSQL."""
    _require_master_access()

    if not _is_postgres_backend():
        st.info("Migração .db → PostgreSQL disponível apenas quando o backend ativo é PostgreSQL.")
        return

    st.error("🚨 **ATENÇÃO: MIGRAÇÃO DESTRUTIVA**")
    st.warning(
        "⚠️ Esta operação recria o schema público do PostgreSQL e sobrescreve completamente os dados atuais."
    )

    uploaded_file = st.file_uploader(
        "Faça upload do arquivo SQLite (.db) para migrar para PostgreSQL",
        type=["db", "sqlite"],
        key="migrar_sqlite_para_postgres",
    )

    if uploaded_file is None:
        return

    if st.button("🚀 Migrar .db para PostgreSQL", type="primary", width="stretch"):
        try:
            with tempfile.NamedTemporaryFile(prefix="bf1_sqlite_migration_", suffix=".db", delete=False) as tmp:
                tmp.write(uploaded_file.getbuffer())
                sqlite_path = Path(tmp.name)

            st.info("🔄 Migrando estrutura e dados do SQLite para PostgreSQL...")
            ok, error, stats = _migrate_sqlite_file_to_postgres(sqlite_path)
            sqlite_path.unlink(missing_ok=True)
            if not ok:
                st.error(f"❌ Falha na migração: {error}")
                return

            st.success("✅ Migração concluída com sucesso!")
            st.info(f"📊 Tabelas migradas: {stats['tables']}")
            st.info(f"📥 Registros migrados: {stats['rows']}")
            st.cache_data.clear()
            st.rerun()
        except Exception as exc:
            st.error(f"❌ Erro durante migração: {exc}")

def main():
    st.title("💾 Backup e Restauração do Banco de Dados")
    st.markdown("""
    - **Download Completo:** Baixe uma cópia limpa do banco inteiro (.db).
    - **Upload Completo:** Substitua todo o banco por arquivo .db (SQLite) ou .sql (dump MySQL/PostgreSQL).
    - **Exportar tabela:** Exporte uma tabela específica (.xlsx).
    - **Importar tabela:** Importe dados para uma tabela específica (sobrescreve).
    
    💡 **Novidade:** Agora aceita arquivos .sql! O sistema converte automaticamente sintaxe MySQL→SQLite.
    """)
    
    # Mostrar info do banco
    st.info(f"📍 Banco de dados: `{DB_PATH.name}` | Status: {'Existe' if DB_PATH.exists() else 'Não encontrado'}")
    
    st.header("Backup/Restauração do arquivo completo")
    col1, col2 = st.columns(2)
    with col1:
        download_db()
    with col2:
        upload_db()
    st.divider()
    st.header("Backup/Restauração de tabelas específicas")
    tab1, tab2 = st.tabs(["Exportar Tabela", "Importar Tabela"])
    with tab1:
        download_tabela()
    with tab2:
        upload_tabela()

    st.divider()
    st.header("Temporadas")
    st.write("Gerencie as temporadas visíveis no sistema. A criação de uma nova temporada fará com que ela possa aparecer em seletores que leem a tabela `temporadas`.")
    col_a, col_b = st.columns([2, 8])
    with col_a:
        if st.button("➕ Criar próxima temporada"):
            new_year = create_next_temporada()
            st.success(f"✅ Temporada {new_year} criada/registrada com sucesso.")
            st.rerun()
    with col_b:
        existing = list_temporadas()
        if existing:
            st.write("Temporadas cadastradas:")
            st.write(", ".join(existing))
        else:
            st.info("Nenhuma temporada cadastrada. Botão acima cria a próxima temporada.")

if __name__ == "__main__":
    main()

# ============ FUNÇÕES DE BACKUP E RESTAURAÇÃO ============

def backup_banco(backup_dir: str = "backups") -> str:
    """
    Cria um backup do banco de dados usando a API de backup do SQLite.
    Isso garante que todos os dados do WAL sejam incluídos no backup.
    
    Args:
        backup_dir: Diretório para armazenar backups
    
    Returns:
        Caminho do arquivo de backup criado
    """
    if DB_BACKEND == "postgres":
        raise RuntimeError("backup_banco não suporta PostgreSQL; use backup nativo do banco gerenciado")

    backup_path = Path(backup_dir)
    backup_path.mkdir(exist_ok=True)
    
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    backup_file = backup_path / f"backup_{timestamp}.db"
    
    # Usar API de backup do SQLite para garantir integridade (inclui WAL)
    source_conn = sqlite3.connect(str(DB_PATH), timeout=30)
    dest_conn = sqlite3.connect(str(backup_file), timeout=30)
    
    try:
        # Consolidar WAL antes do backup
        source_conn.execute("PRAGMA wal_checkpoint(TRUNCATE)")
        source_conn.backup(dest_conn)
        dest_conn.execute("VACUUM")
    finally:
        source_conn.close()
        dest_conn.close()
    
    return str(backup_file)

def restaurar_backup(backup_file: str) -> bool:
    """
    Restaura o banco de dados a partir de um backup usando a API de backup do SQLite.
    Isso garante que todos os dados do WAL sejam tratados corretamente.
    
    Args:
        backup_file: Caminho do arquivo de backup
    
    Returns:
        True se restaurado com sucesso, False caso contrário
    """
    try:
        if DB_BACKEND == "postgres":
            return False

        if not Path(backup_file).exists():
            return False
        
        # Fechar pool para evitar locks
        from db.connection_pool import close_pool
        try:
            close_pool()
        except:
            pass
        
        # Remover arquivos WAL/SHM antigos que podem causar problemas
        wal_file = Path(str(DB_PATH) + "-wal")
        shm_file = Path(str(DB_PATH) + "-shm")
        if wal_file.exists():
            wal_file.unlink()
        if shm_file.exists():
            shm_file.unlink()
        
        # Usar API de backup do SQLite para garantir integridade
        source_conn = sqlite3.connect(str(backup_file), timeout=30)
        dest_conn = sqlite3.connect(str(DB_PATH), timeout=30)
        
        try:
            source_conn.execute("PRAGMA wal_checkpoint(TRUNCATE)")
            source_conn.backup(dest_conn)
            dest_conn.execute("PRAGMA wal_checkpoint(TRUNCATE)")
            dest_conn.execute("VACUUM")
        finally:
            source_conn.close()
            dest_conn.close()
        
        # Remover arquivos WAL/SHM que podem ter sido criados
        if wal_file.exists():
            wal_file.unlink()
        if shm_file.exists():
            shm_file.unlink()
        
        return True
    except Exception as e:
        print(f"Erro ao restaurar backup: {e}")
        return False


# ============ FUNÇÕES DE TEMPORADAS ============
def ensure_temporadas_table() -> None:
    """Garante que a tabela `temporadas` exista no banco de dados."""
    try:
        with db_connect() as conn:
            c = conn.cursor()
            c.execute('''
                CREATE TABLE IF NOT EXISTS temporadas (
                    temporada TEXT PRIMARY KEY,
                    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                )
            ''')
            conn.commit()
    except Exception as e:
        st.error(f"❌ Erro ao garantir tabela 'temporadas': {e}")


def create_next_temporada() -> str:
    """Cria (se ainda não existir) a temporada do próximo ano (ano atual + 1).

    Retorna a string do ano criado (ex: '2026').
    """
    from datetime import datetime as _dt
    next_year = _dt.now().year + 1
    ensure_temporadas_table()
    try:
        with db_connect() as conn:
            c = conn.cursor()
            if _is_postgres_backend():
                c.execute(
                    "INSERT INTO temporadas (temporada) VALUES (?) ON CONFLICT (temporada) DO NOTHING",
                    (str(next_year),),
                )
            else:
                c.execute("INSERT OR IGNORE INTO temporadas (temporada) VALUES (?)", (str(next_year),))
            conn.commit()
    except Exception as e:
        st.error(f"❌ Erro ao criar temporada {next_year}: {e}")
    return str(next_year)


def list_temporadas() -> list:
    """Retorna lista de temporadas cadastradas (strings)."""
    try:
        with db_connect() as conn:
            c = conn.cursor()
            if _is_postgres_backend():
                c.execute(
                    """
                    SELECT 1
                    FROM information_schema.tables
                    WHERE table_schema = 'public' AND table_name = 'temporadas'
                    """
                )
                if not c.fetchone():
                    return []
            else:
                c.execute("SELECT name FROM sqlite_master WHERE type='table' AND name='temporadas'")
                if not c.fetchone():
                    return []
            c.execute("SELECT temporada FROM temporadas ORDER BY temporada ASC")
            return [str(r[0]) for r in c.fetchall()]
    except Exception as e:
        st.error(f"❌ Erro ao listar temporadas: {e}")
        return []
