"""Helpers de schema e inicialização."""

from __future__ import annotations

import logging
from contextlib import contextmanager

from db.connection_pool import get_pool
from db.migrations import run_migrations

logger = logging.getLogger(__name__)


@contextmanager
def db_connect():
    pool = get_pool()
    with pool.get_connection() as conn:
        yield conn


def get_table_columns(conn, table_name: str) -> list[str]:
    cur = conn.cursor()
    cur.execute(
        """
        SELECT column_name
        FROM information_schema.columns
        WHERE table_name = %s
        ORDER BY ordinal_position
        """,
        (table_name,),
    )
    cols = [row["column_name"] for row in cur.fetchall()]
    cur.close()
    return cols


def table_exists(conn, table_name: str) -> bool:
    cur = conn.cursor()
    cur.execute(
        """
        SELECT 1
        FROM information_schema.tables
        WHERE table_schema = 'public'
          AND table_name = %s
        LIMIT 1
        """,
        (table_name,),
    )
    exists = cur.fetchone() is not None
    cur.close()
    return exists


def init_db() -> None:
    ddl = """
        CREATE TABLE IF NOT EXISTS usuarios (
            id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            nome                 TEXT NOT NULL,
            email                TEXT UNIQUE NOT NULL,
            senha_hash           TEXT NOT NULL,
            perfil               TEXT DEFAULT 'participante',
            status               TEXT DEFAULT 'ativo',
            must_change_password BOOLEAN DEFAULT FALSE,
            faltas               INTEGER DEFAULT 0,
            criado_em            TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );

        CREATE TABLE IF NOT EXISTS pilotos (
            id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            nome    TEXT UNIQUE NOT NULL,
            equipe  TEXT DEFAULT '',
            status  TEXT DEFAULT 'Ativo',
            numero  INTEGER DEFAULT 0
        );

        CREATE TABLE IF NOT EXISTS provas (
            id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            nome            TEXT NOT NULL,
            data            TEXT,
            horario_prova   TEXT DEFAULT '',
            tipo            TEXT DEFAULT 'Normal',
            status          TEXT DEFAULT 'Pendente',
            temporada       TEXT
        );

        CREATE TABLE IF NOT EXISTS apostas (
            id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            usuario_id  INTEGER NOT NULL REFERENCES usuarios(id),
            prova_id    INTEGER NOT NULL REFERENCES provas(id),
            data_envio  TEXT,
            pilotos     TEXT,
            fichas      TEXT,
            piloto_11   TEXT,
            nome_prova  TEXT,
            automatica  INTEGER DEFAULT 0,
            temporada   TEXT
        );

        CREATE TABLE IF NOT EXISTS resultados (
            prova_id    INTEGER PRIMARY KEY REFERENCES provas(id),
            posicoes    TEXT
        );

        CREATE TABLE IF NOT EXISTS posicoes_participantes (
            id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            prova_id    INTEGER NOT NULL REFERENCES provas(id),
            usuario_id  INTEGER NOT NULL REFERENCES usuarios(id),
            posicao     INTEGER,
            pontos      REAL,
            temporada   TEXT
        );

        CREATE TABLE IF NOT EXISTS regras (
            id                      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            temporada               TEXT NOT NULL,
            tipo_prova              TEXT NOT NULL DEFAULT 'Normal',
            qtd_minima_pilotos      INTEGER DEFAULT 3,
            quantidade_fichas       INTEGER DEFAULT 15,
            fichas_por_piloto       INTEGER DEFAULT 15,
            mesma_equipe            BOOLEAN DEFAULT FALSE,
            pontos_11_colocado      INTEGER DEFAULT 25,
            penalidade_abandono     BOOLEAN DEFAULT FALSE,
            pontos_penalidade       INTEGER DEFAULT 0,
            pontos_dobrada          BOOLEAN DEFAULT FALSE,
            pontos_posicoes         TEXT,
            pontos_sprint_posicoes  TEXT,
            UNIQUE(temporada, tipo_prova)
        );
    """
    with db_connect() as conn:
        cur = conn.cursor()
        cur.execute(ddl)
        cur.close()
        conn.commit()
    logger.info("init_db concluido")

__all__ = [
    "db_connect",
    "get_table_columns",
    "table_exists",
    "init_db",
    "run_migrations",
]
