# Este arquivo é gerenciado pelo projeto BF1Homol.
# NÃO EDITE MANUALMENTE ESTE CABEÇALHO.
#
# Nota sobre função `table_exists`:
#   Adicionada para suporte às migrations. Já estava presente no
#   módulo; esta versão garante export explícito.

from __future__ import annotations

import logging
from contextlib import contextmanager
from datetime import datetime
from typing import Optional

import bcrypt
import pandas as pd

from db.connection_pool import get_pool

logger = logging.getLogger(__name__)

# Allowlists de colunas válidas para funções de update dinâmico.
# fix(crítico #3): evita SQL injection via nomes de campo arbitrários em kwargs.
_COLUNAS_USUARIOS_VALIDAS: frozenset[str] = frozenset({
    "nome", "email", "senha_hash", "perfil", "status",
    "must_change_password", "faltas", "criado_em",
})
_COLUNAS_PILOTOS_VALIDAS: frozenset[str] = frozenset({
    "nome", "equipe", "status", "numero",
})
_COLUNAS_PROVAS_VALIDAS: frozenset[str] = frozenset({
    "nome", "data", "horario_prova", "tipo", "status", "temporada",
})


# ---------------------------------------------------------------------------
# Conexão
# ---------------------------------------------------------------------------

@contextmanager
def db_connect():
    pool = get_pool()
    with pool.get_connection() as conn:
        yield conn


# ---------------------------------------------------------------------------
# Helper interno: query -> DataFrame
# Substitui pd.read_sql que é incompatível com psycopg3 (dict_row).
# Todos os DataFrame helpers devem usar esta função.
# ---------------------------------------------------------------------------

def _query_to_df(query: str, params: tuple | None = None) -> pd.DataFrame:
    """Executa query via cursor psycopg3 e retorna DataFrame.

    pd.read_sql é incompatível com psycopg3 quando row_factory=dict_row:
    o pandas itera as chaves do dict em vez dos valores, resultando em
    células com o nome da coluna repetido em cada linha.

    fix: quando fetchall() retorna lista vazia, usa cur.description para
    preservar os nomes das colunas no DataFrame retornado — evita KeyError
    ao filtrar colunas (ex: 'usuario_id') em DataFrames vazios.
    """
    with db_connect() as conn:
        cur = conn.cursor()
        cur.execute(query, params or ())
        rows = cur.fetchall() or []
        if not rows:
            # Preserva schema: extrai nomes das colunas do cursor mesmo sem linhas
            col_names = [desc[0] for desc in (cur.description or [])]
            cur.close()
            return pd.DataFrame(columns=col_names)
        cur.close()
    return pd.DataFrame([dict(r) for r in rows])


# ---------------------------------------------------------------------------
# Schema helpers
# ---------------------------------------------------------------------------

def get_table_columns(conn, table_name: str) -> list[str]:
    """Retorna lista de nomes de colunas de uma tabela."""
    cur = conn.cursor()
    cur.execute(
        """
        SELECT column_name
        FROM information_schema.columns
        WHERE table_name = %s
        ORDER BY ordinal_position
        """,
        (table_name,),
    )
    cols = [row["column_name"] for row in cur.fetchall()]
    cur.close()
    return cols


def table_exists(conn, table_name: str) -> bool:
    """Verifica se uma tabela existe no schema público."""
    cur = conn.cursor()
    cur.execute(
        """
        SELECT 1
        FROM information_schema.tables
        WHERE table_schema = 'public'
          AND table_name = %s
        LIMIT 1
        """,
        (table_name,),
    )
    exists = cur.fetchone() is not None
    cur.close()
    return exists


# ---------------------------------------------------------------------------
# Init DB (cria tabelas base)
# ---------------------------------------------------------------------------

def init_db() -> None:
    """Cria tabelas base se ainda não existirem.

    IMPORTANTE: este DDL deve estar sempre em paridade com as migrations.
    Ao adicionar uma coluna via migration, adicione-a aqui também para que
    bancos criados do zero (sem rodar migrations) tenham o schema completo.

    fix(crítico): coluna de senha nomeada como `senha_hash` para paridade
    com o schema real do banco de produção (confirmado via dump).
    """
    ddl = """
        CREATE TABLE IF NOT EXISTS usuarios (
            id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            nome                 TEXT NOT NULL,
            email                TEXT UNIQUE NOT NULL,
            senha_hash           TEXT NOT NULL,
            perfil               TEXT DEFAULT 'participante',
            status               TEXT DEFAULT 'ativo',
            -- fix(#12): coluna presente nas migrations; adicionada ao DDL base
            -- para garantir paridade em bancos criados do zero sem migrations.
            must_change_password BOOLEAN DEFAULT FALSE,
            faltas               INTEGER DEFAULT 0,
            criado_em            TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );

        CREATE TABLE IF NOT EXISTS pilotos (
            id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            nome    TEXT UNIQUE NOT NULL,
            equipe  TEXT DEFAULT '',
            status  TEXT DEFAULT 'Ativo',
            numero  INTEGER DEFAULT 0
        );

        CREATE TABLE IF NOT EXISTS provas (
            id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            nome            TEXT NOT NULL,
            data            TEXT,
            horario_prova   TEXT DEFAULT '',
            tipo            TEXT DEFAULT 'Normal',
            status          TEXT DEFAULT 'Pendente',
            temporada       TEXT
        );

        CREATE TABLE IF NOT EXISTS apostas (
            id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            usuario_id  INTEGER NOT NULL REFERENCES usuarios(id),
            prova_id    INTEGER NOT NULL REFERENCES provas(id),
            data_envio  TEXT,
            pilotos     TEXT,
            fichas      TEXT,
            piloto_11   TEXT,
            nome_prova  TEXT,
            automatica  INTEGER DEFAULT 0,
            temporada   TEXT
        );

        CREATE TABLE IF NOT EXISTS resultados (
            prova_id    INTEGER PRIMARY KEY REFERENCES provas(id),
            posicoes    TEXT
        );

        CREATE TABLE IF NOT EXISTS posicoes_participantes (
            id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            prova_id    INTEGER NOT NULL REFERENCES provas(id),
            usuario_id  INTEGER NOT NULL REFERENCES usuarios(id),
            posicao     INTEGER,
            pontos      REAL,
            temporada   TEXT
        );

        CREATE TABLE IF NOT EXISTS regras (
            id                      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            temporada               TEXT NOT NULL,
            tipo_prova              TEXT NOT NULL DEFAULT 'Normal',
            qtd_minima_pilotos      INTEGER DEFAULT 3,
            quantidade_fichas       INTEGER DEFAULT 15,
            fichas_por_piloto       INTEGER DEFAULT 15,
            mesma_equipe            BOOLEAN DEFAULT FALSE,
            pontos_11_colocado      INTEGER DEFAULT 25,
            penalidade_abandono     BOOLEAN DEFAULT FALSE,
            pontos_penalidade       INTEGER DEFAULT 0,
            pontos_dobrada          BOOLEAN DEFAULT FALSE,
            pontos_posicoes         TEXT,
            pontos_sprint_posicoes  TEXT,
            UNIQUE(temporada, tipo_prova)
        );
    """
    with db_connect() as conn:
        cur = conn.cursor()
        cur.execute(ddl)
        cur.close()
        conn.commit()
    logger.info("✓ init_db concluído")


# ---------------------------------------------------------------------------
# Password helpers
# ---------------------------------------------------------------------------

def hash_password(plain: str) -> str:
    return bcrypt.hashpw(plain.encode(), bcrypt.gensalt()).decode()


def check_password(plain: str, hashed: str) -> bool:
    try:
        return bcrypt.checkpw(plain.encode(), hashed.encode())
    except Exception:
        return False


# ---------------------------------------------------------------------------
# User helpers
# ---------------------------------------------------------------------------

def get_user_by_email(email: str) -> Optional[dict]:
    from db.repo_users import get_user_by_email as _repo_get_user_by_email

    return _repo_get_user_by_email(email)


def get_user_by_id(user_id: int) -> Optional[dict]:
    from db.repo_users import get_user_by_id as _repo_get_user_by_id

    return _repo_get_user_by_id(user_id)


def get_master_user() -> Optional[dict]:
    from db.repo_users import get_master_user as _repo_get_master_user

    return _repo_get_master_user()


def cadastrar_usuario(nome: str, email: str, senha: str, perfil: str = "participante") -> bool:
    from db.repo_users import cadastrar_usuario as _repo_cadastrar_usuario

    return _repo_cadastrar_usuario(nome, email, senha, perfil)


def autenticar_usuario(email: str, senha: str) -> Optional[dict]:
    from db.repo_users import autenticar_usuario as _repo_autenticar_usuario

    return _repo_autenticar_usuario(email, senha)


def update_user_email(user_id: int, novo_email: str) -> bool:
    from db.repo_users import update_user_email as _repo_update_user_email

    return _repo_update_user_email(user_id, novo_email)


def update_user_password(user_id: int, nova_senha: str, must_change_password: bool = False) -> bool:
    from db.repo_users import update_user_password as _repo_update_user_password

    return _repo_update_user_password(user_id, nova_senha, must_change_password)


def update_usuario(user_id: int, **campos) -> bool:
    """Atualiza campos arbitrários de um usuário.

    Uso: update_usuario(1, nome='Novo Nome', perfil='admin')

    fix(crítico #3): valida cada chave contra allowlist antes de montar
    o SET clause — impede SQL injection via nomes de campo arbitrários.
    """
    if not campos:
        return False
    campos_invalidos = set(campos) - _COLUNAS_USUARIOS_VALIDAS
    if campos_invalidos:
        logger.error("update_usuario: colunas não permitidas rejeitadas: %s", campos_invalidos)
        raise ValueError(f"Colunas não permitidas em update_usuario: {campos_invalidos}")
    set_clause = ", ".join(f"{k} = %s" for k in campos)
    values = list(campos.values()) + [user_id]
    try:
        with db_connect() as conn:
            cur = conn.cursor()
            cur.execute(f"UPDATE usuarios SET {set_clause} WHERE id = %s", values)
            cur.close()
            conn.commit()
        return True
    except Exception as exc:
        logger.error("update_usuario falhou: %s", exc)
        return False


def delete_usuario(user_id: int) -> bool:
    """Remove um usuário pelo ID."""
    try:
        with db_connect() as conn:
            cur = conn.cursor()
            cur.execute("DELETE FROM usuarios WHERE id = %s", (user_id,))
            cur.close()
            conn.commit()
        return True
    except Exception as exc:
        logger.error("delete_usuario falhou: %s", exc)
        return False


# ---------------------------------------------------------------------------
# DataFrame helpers  (todos via _query_to_df — nunca pd.read_sql)
# ---------------------------------------------------------------------------

def get_usuarios_df() -> pd.DataFrame:
    from db.repo_users import get_usuarios_df as _repo_get_usuarios_df

    return _repo_get_usuarios_df()


def get_pilotos_df() -> pd.DataFrame:
    return _query_to_df("SELECT * FROM pilotos ORDER BY nome")


def get_provas_df(temporada: Optional[str] = None) -> pd.DataFrame:
    from db.repo_races import get_provas_df as _repo_get_provas_df

    return _repo_get_provas_df(temporada)


def get_apostas_df(temporada: Optional[str] = None) -> pd.DataFrame:
    from db.repo_bets import get_apostas_df as _repo_get_apostas_df

    return _repo_get_apostas_df(temporada)


def get_resultados_df(temporada: Optional[str] = None) -> pd.DataFrame:
    from db.repo_races import get_resultados_df as _repo_get_resultados_df

    return _repo_get_resultados_df(temporada)


def get_posicoes_participantes_df(temporada: Optional[str] = None) -> pd.DataFrame:
    """Retorna DataFrame de posicoes_participantes, filtrando por temporada quando informada."""
    if temporada:
        return _query_to_df(
            "SELECT * FROM posicoes_participantes WHERE temporada = %s ORDER BY prova_id, posicao",
            (temporada,),
        )
    return _query_to_df("SELECT * FROM posicoes_participantes ORDER BY prova_id, posicao")


# ---------------------------------------------------------------------------
# Pilotos helpers
# ---------------------------------------------------------------------------

def add_piloto(nome: str, equipe: str = "", status: str = "Ativo", numero: int = 0) -> bool:
    """Insere um piloto. Retorna False se já existir."""
    try:
        with db_connect() as conn:
            cur = conn.cursor()
            cur.execute(
                "INSERT INTO pilotos (nome, equipe, status, numero) VALUES (%s, %s, %s, %s)",
                (nome, equipe, status, numero),
            )
            cur.close()
            conn.commit()
        return True
    except Exception as exc:
        logger.warning("add_piloto falhou: %s", exc)
        return False


def update_piloto(piloto_id: int, **campos) -> bool:
    """Atualiza campos de um piloto.

    fix(crítico #3): valida cada chave contra allowlist antes de montar
    o SET clause — impede SQL injection via nomes de campo arbitrários.
    """
    if not campos:
        return False
    campos_invalidos = set(campos) - _COLUNAS_PILOTOS_VALIDAS
    if campos_invalidos:
        logger.error("update_piloto: colunas não permitidas rejeitadas: %s", campos_invalidos)
        raise ValueError(f"Colunas não permitidas em update_piloto: {campos_invalidos}")
    set_clause = ", ".join(f"{k} = %s" for k in campos)
    values = list(campos.values()) + [piloto_id]
    try:
        with db_connect() as conn:
            cur = conn.cursor()
            cur.execute(f"UPDATE pilotos SET {set_clause} WHERE id = %s", values)
            cur.close()
            conn.commit()
        return True
    except Exception as exc:
        logger.error("update_piloto falhou: %s", exc)
        return False


def delete_piloto(piloto_id: int) -> bool:
    """Remove um piloto pelo ID."""
    try:
        with db_connect() as conn:
            cur = conn.cursor()
            cur.execute("DELETE FROM pilotos WHERE id = %s", (piloto_id,))
            cur.close()
            conn.commit()
        return True
    except Exception as exc:
        logger.error("delete_piloto falhou: %s", exc)
        return False


# ---------------------------------------------------------------------------
# Provas helpers
# ---------------------------------------------------------------------------

def add_prova(nome: str, data: str, horario_prova: str = "", tipo: str = "Normal",
              status: str = "Pendente", temporada: Optional[str] = None) -> bool:
    """Insere uma prova."""
    try:
        with db_connect() as conn:
            cur = conn.cursor()
            cur.execute(
                "INSERT INTO provas (nome, data, horario_prova, tipo, status, temporada) "
                "VALUES (%s, %s, %s, %s, %s, %s)",
                (nome, data, horario_prova, tipo, status, temporada),
            )
            cur.close()
            conn.commit()
        return True
    except Exception as exc:
        logger.error("add_prova falhou: %s", exc)
        return False


def update_prova(prova_id: int, **campos) -> bool:
    """Atualiza campos de uma prova.

    fix(crítico #3): valida cada chave contra allowlist antes de montar
    o SET clause — impede SQL injection via nomes de campo arbitrários.
    """
    if not campos:
        return False
    campos_invalidos = set(campos) - _COLUNAS_PROVAS_VALIDAS
    if campos_invalidos:
        logger.error("update_prova: colunas não permitidas rejeitadas: %s", campos_invalidos)
        raise ValueError(f"Colunas não permitidas em update_prova: {campos_invalidos}")
    set_clause = ", ".join(f"{k} = %s" for k in campos)
    values = list(campos.values()) + [prova_id]
    try:
        with db_connect() as conn:
            cur = conn.cursor()
            cur.execute(f"UPDATE provas SET {set_clause} WHERE id = %s", values)
            cur.close()
            conn.commit()
        return True
    except Exception as exc:
        logger.error("update_prova falhou: %s", exc)
        return False


def delete_prova(prova_id: int) -> bool:
    """Remove uma prova pelo ID."""
    try:
        with db_connect() as conn:
            cur = conn.cursor()
            cur.execute("DELETE FROM provas WHERE id = %s", (prova_id,))
            cur.close()
            conn.commit()
        return True
    except Exception as exc:
        logger.error("delete_prova falhou: %s", exc)
        return False


# ---------------------------------------------------------------------------
# Race / schedule helpers
# ---------------------------------------------------------------------------

def get_horario_prova(prova_id: int) -> tuple[Optional[str], Optional[str], Optional[str]]:
    """Retorna (nome_prova, data, horario_prova) ou (None, None, None)."""
    with db_connect() as conn:
        cur = conn.cursor()
        cur.execute(
            "SELECT nome, data, horario_prova FROM provas WHERE id = %s",
            (prova_id,),
        )
        row = cur.fetchone()
        cur.close()
    if row:
        return row["nome"], row["data"], row["horario_prova"]
    return None, None, None


# ---------------------------------------------------------------------------
# Resultados helpers
# ---------------------------------------------------------------------------

def salvar_resultado(prova_id: int, posicoes: str, abandono_pilotos: str = "") -> bool:
    """Insere ou atualiza resultado de uma prova."""
    try:
        with db_connect() as conn:
            cur = conn.cursor()
            cur.execute(
                """
                INSERT INTO resultados (prova_id, posicoes, abandono_pilotos)
                VALUES (%s, %s, %s)
                ON CONFLICT (prova_id) DO UPDATE
                    SET posicoes = EXCLUDED.posicoes,
                        abandono_pilotos = EXCLUDED.abandono_pilotos
                """,
                (prova_id, posicoes, abandono_pilotos),
            )
            cur.close()
            conn.commit()
        return True
    except Exception as exc:
        logger.error("salvar_resultado falhou: %s", exc)
        return False


# ---------------------------------------------------------------------------
# Aposta log helpers
# ---------------------------------------------------------------------------

def registrar_log_aposta(
    usuario_id: int,
    prova_id: int,
    apostador: str,
    pilotos: str,
    aposta: str,
    nome_prova: str,
    piloto_11: str,
    tipo_aposta: int,
    automatica: int,
    horario,
    ip_address: Optional[str] = None,
    temporada: Optional[str] = None,
    status: str = "Registrada",
) -> None:
    try:
        horario_dt = horario if isinstance(horario, datetime) else None
        if horario_dt is None:
            try:
                horario_dt = pd.to_datetime(horario, errors="coerce").to_pydatetime() if horario is not None else None
            except Exception:
                horario_dt = None
        if horario_dt is None:
            logger.error(
                "registrar_log_aposta ignorado: horario ausente/invalido para usuario_id=%s prova_id=%s",
                usuario_id,
                prova_id,
            )
            return

        data_txt = horario_dt.strftime("%Y-%m-%d")

        with db_connect() as conn:
            cur = conn.cursor()
            cols = get_table_columns(conn, "log_apostas")
            if not cols:
                cur.close()
                return
            cur.execute(
                """
                INSERT INTO log_apostas
                    (usuario_id, prova_id, apostador, aposta, nome_prova,
                     pilotos, piloto_11, tipo_aposta, automatica, data, horario,
                     ip_address, temporada, status)
                VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
                """,
                (
                    usuario_id, prova_id, apostador, aposta, nome_prova,
                    pilotos, piloto_11, tipo_aposta, automatica, data_txt, horario_dt,
                    ip_address, temporada, status,
                ),
            )
            cur.close()
            conn.commit()
    except Exception as exc:
        logger.debug("registrar_log_aposta falhou: %s", exc)


def log_aposta_existe(usuario_id: int, prova_id: int, temporada: Optional[str] = None) -> bool:
    with db_connect() as conn:
        cur = conn.cursor()
        if temporada:
            cur.execute(
                "SELECT 1 FROM log_apostas WHERE usuario_id=%s AND prova_id=%s AND temporada=%s LIMIT 1",
                (usuario_id, prova_id, temporada),
            )
        else:
            cur.execute(
                "SELECT 1 FROM log_apostas WHERE usuario_id=%s AND prova_id=%s LIMIT 1",
                (usuario_id, prova_id),
            )
        exists = cur.fetchone() is not None
        cur.close()
        return exists


# ---------------------------------------------------------------------------
# Histórico de status de usuários
# ---------------------------------------------------------------------------

def _usuarios_status_historico_exists(conn) -> bool:
    """Verifica se a tabela usuarios_status_historico existe."""
    return table_exists(conn, "usuarios_status_historico")


def usuarios_status_historico_disponivel() -> bool:
    """Indica se há histórico de status de usuários para filtros sazonais confiáveis."""
    with db_connect() as conn:
        return _usuarios_status_historico_exists(conn)


def registrar_historico_status_usuario(
    usuario_id: int,
    novo_status: str,
    alterado_por: Optional[int] = None,
    motivo: Optional[str] = None,
    data_referencia: Optional[str] = None,
) -> None:
    """Registra alteração de status do usuário no histórico."""
    if data_referencia is None:
        data_referencia = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    with db_connect() as conn:
        cursor = conn.cursor()
        if not _usuarios_status_historico_exists(conn):
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS usuarios_status_historico (
                    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    usuario_id  INTEGER NOT NULL,
                    status      TEXT NOT NULL,
                    inicio_em   TIMESTAMP NOT NULL,
                    fim_em      TIMESTAMP,
                    alterado_por INTEGER,
                    motivo      TEXT,
                    FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
                )
            """)

        cursor.execute(
            "SELECT id, status FROM usuarios_status_historico "
            "WHERE usuario_id = %s AND fim_em IS NULL ORDER BY inicio_em DESC LIMIT 1",
            (usuario_id,),
        )
        row = cursor.fetchone()
        if row and row["status"] == novo_status:
            cursor.close()
            return

        if row:
            cursor.execute(
                "UPDATE usuarios_status_historico SET fim_em = %s WHERE id = %s",
                (data_referencia, row["id"]),
            )

        cursor.execute(
            """
            INSERT INTO usuarios_status_historico
                (usuario_id, status, inicio_em, fim_em, alterado_por, motivo)
            VALUES (%s, %s, %s, NULL, %s, %s)
            """,
            (usuario_id, novo_status, data_referencia, alterado_por, motivo),
        )
        cursor.close()
        conn.commit()


def get_participantes_temporada_df(temporada: Optional[str] = None) -> pd.DataFrame:
    from db.repo_users import get_participantes_temporada_df as _repo_get_participantes_temporada_df

    return _repo_get_participantes_temporada_df(temporada)


def get_usuario_temporadas_ativas(user_id: int) -> list[str]:
    from db.repo_users import get_usuario_temporadas_ativas as _repo_get_usuario_temporadas_ativas

    return _repo_get_usuario_temporadas_ativas(user_id)
