# Este arquivo é gerenciado pelo projeto BF1Homol.
# NÃO EDITE MANUALMENTE ESTE CABEÇALHO.
#
# Nota sobre função `table_exists`:
#   Adicionada para suporte às migrations. Já estava presente no
#   módulo; esta versão garante export explícito.

from __future__ import annotations

import hashlib
import json
import logging
import os
import threading
from contextlib import contextmanager
from datetime import datetime
from typing import Optional

import bcrypt
import pandas as pd
import psycopg2
import psycopg2.extras

from db.connection_pool import get_pool

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Cache simples thread-safe (TTL em segundos)
# ---------------------------------------------------------------------------
_cache_lock = threading.Lock()
_cache: dict = {}


def _cache_get(key: str) -> Optional[object]:
    with _cache_lock:
        entry = _cache.get(key)
        if entry is None:
            return None
        value, expires_at = entry
        if datetime.now().timestamp() > expires_at:
            del _cache[key]
            return None
        return value


def _cache_set(key: str, value: object, ttl: int = 30) -> None:
    with _cache_lock:
        _cache[key] = (value, datetime.now().timestamp() + ttl)


def _cache_invalidate(prefix: str = "") -> None:
    with _cache_lock:
        keys = [k for k in _cache if k.startswith(prefix)]
        for k in keys:
            del _cache[k]


# ---------------------------------------------------------------------------
# Conexão
# ---------------------------------------------------------------------------

@contextmanager
def db_connect():
    pool = get_pool()
    with pool.get_connection() as conn:
        yield conn


# ---------------------------------------------------------------------------
# Schema helpers
# ---------------------------------------------------------------------------

def get_table_columns(conn, table_name: str) -> list[str]:
    """Retorna lista de nomes de colunas de uma tabela."""
    cur = conn.cursor()
    cur.execute(
        """
        SELECT column_name
        FROM information_schema.columns
        WHERE table_name = %s
        ORDER BY ordinal_position
        """,
        (table_name,),
    )
    return [row["column_name"] for row in cur.fetchall()]


def table_exists(conn, table_name: str) -> bool:
    """Verifica se uma tabela existe no schema público."""
    cur = conn.cursor()
    cur.execute(
        """
        SELECT 1
        FROM information_schema.tables
        WHERE table_schema = 'public'
          AND table_name = %s
        LIMIT 1
        """,
        (table_name,),
    )
    return cur.fetchone() is not None


# ---------------------------------------------------------------------------
# Init DB (cria tabelas base)
# ---------------------------------------------------------------------------

def init_db() -> None:
    """Cria tabelas base se ainda não existirem."""
    ddl = """
        CREATE TABLE IF NOT EXISTS usuarios (
            id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            nome        TEXT NOT NULL,
            email       TEXT UNIQUE NOT NULL,
            senha       TEXT NOT NULL,
            perfil      TEXT DEFAULT 'participante',
            status      TEXT DEFAULT 'ativo',
            criado_em   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );

        CREATE TABLE IF NOT EXISTS pilotos (
            id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            nome    TEXT UNIQUE NOT NULL,
            equipe  TEXT DEFAULT '',
            status  TEXT DEFAULT 'Ativo',
            numero  INTEGER DEFAULT 0
        );

        CREATE TABLE IF NOT EXISTS provas (
            id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            nome            TEXT NOT NULL,
            data            TEXT,
            horario_prova   TEXT DEFAULT '',
            tipo            TEXT DEFAULT 'Normal',
            status          TEXT DEFAULT 'Pendente',
            temporada       TEXT
        );

        CREATE TABLE IF NOT EXISTS apostas (
            id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            usuario_id  INTEGER NOT NULL REFERENCES usuarios(id),
            prova_id    INTEGER NOT NULL REFERENCES provas(id),
            data_envio  TEXT,
            pilotos     TEXT,
            fichas      TEXT,
            piloto_11   TEXT,
            nome_prova  TEXT,
            automatica  INTEGER DEFAULT 0,
            temporada   TEXT
        );

        CREATE TABLE IF NOT EXISTS resultados (
            prova_id    INTEGER PRIMARY KEY REFERENCES provas(id),
            posicoes    TEXT
        );

        CREATE TABLE IF NOT EXISTS posicoes_participantes (
            id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            prova_id    INTEGER NOT NULL REFERENCES provas(id),
            usuario_id  INTEGER NOT NULL REFERENCES usuarios(id),
            posicao     INTEGER,
            pontos      REAL,
            temporada   TEXT
        );

        CREATE TABLE IF NOT EXISTS regras (
            id                      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            temporada               TEXT NOT NULL,
            tipo_prova              TEXT NOT NULL DEFAULT 'Normal',
            qtd_minima_pilotos      INTEGER DEFAULT 3,
            quantidade_fichas       INTEGER DEFAULT 15,
            fichas_por_piloto       INTEGER DEFAULT 15,
            mesma_equipe            BOOLEAN DEFAULT FALSE,
            pontos_11_colocado      INTEGER DEFAULT 25,
            penalidade_abandono     BOOLEAN DEFAULT FALSE,
            pontos_penalidade       INTEGER DEFAULT 0,
            pontos_dobrada          BOOLEAN DEFAULT FALSE,
            pontos_posicoes         TEXT,
            pontos_sprint_posicoes  TEXT,
            UNIQUE(temporada, tipo_prova)
        );
    """
    with db_connect() as conn:
        cur = conn.cursor()
        cur.execute(ddl)
        conn.commit()
    logger.info("✓ init_db concluído")


# ---------------------------------------------------------------------------
# Password helpers
# ---------------------------------------------------------------------------

def hash_password(plain: str) -> str:
    return bcrypt.hashpw(plain.encode(), bcrypt.gensalt()).decode()


def check_password(plain: str, hashed: str) -> bool:
    try:
        return bcrypt.checkpw(plain.encode(), hashed.encode())
    except Exception:
        return False


# ---------------------------------------------------------------------------
# User helpers
# ---------------------------------------------------------------------------

def get_user_by_email(email: str) -> Optional[dict]:
    with db_connect() as conn:
        cur = conn.cursor()
        cur.execute("SELECT * FROM usuarios WHERE email = %s", (email,))
        row = cur.fetchone()
        return dict(row) if row else None


def get_user_by_id(user_id: int) -> Optional[dict]:
    with db_connect() as conn:
        cur = conn.cursor()
        cur.execute("SELECT * FROM usuarios WHERE id = %s", (user_id,))
        row = cur.fetchone()
        return dict(row) if row else None


def get_master_user() -> Optional[dict]:
    with db_connect() as conn:
        cur = conn.cursor()
        cur.execute("SELECT * FROM usuarios WHERE perfil = 'master' LIMIT 1")
        row = cur.fetchone()
        return dict(row) if row else None


def cadastrar_usuario(nome: str, email: str, senha: str, perfil: str = "participante") -> bool:
    try:
        hashed = hash_password(senha)
        with db_connect() as conn:
            cur = conn.cursor()
            cur.execute(
                "INSERT INTO usuarios (nome, email, senha, perfil) VALUES (%s, %s, %s, %s)",
                (nome, email, hashed, perfil),
            )
            conn.commit()
        return True
    except Exception as exc:
        logger.warning("cadastrar_usuario falhou: %s", exc)
        return False


def autenticar_usuario(email: str, senha: str) -> Optional[dict]:
    user = get_user_by_email(email)
    if user and check_password(senha, user["senha"]):
        return user
    return None


# ---------------------------------------------------------------------------
# DataFrame helpers
# ---------------------------------------------------------------------------

def get_usuarios_df() -> pd.DataFrame:
    with db_connect() as conn:
        return pd.read_sql("SELECT * FROM usuarios", conn)


def get_pilotos_df() -> pd.DataFrame:
    with db_connect() as conn:
        return pd.read_sql("SELECT * FROM pilotos ORDER BY nome", conn)


def get_provas_df(temporada: Optional[str] = None) -> pd.DataFrame:
    with db_connect() as conn:
        if temporada:
            return pd.read_sql(
                "SELECT * FROM provas WHERE temporada = %s ORDER BY id",
                conn,
                params=(temporada,),
            )
        return pd.read_sql("SELECT * FROM provas ORDER BY id", conn)


def get_apostas_df(temporada: Optional[str] = None) -> pd.DataFrame:
    with db_connect() as conn:
        if temporada:
            return pd.read_sql(
                "SELECT * FROM apostas WHERE temporada = %s",
                conn,
                params=(temporada,),
            )
        return pd.read_sql("SELECT * FROM apostas", conn)


def get_resultados_df(temporada: Optional[str] = None) -> pd.DataFrame:
    """
    Retorna DataFrame de resultados.
    Quando a coluna `posicoes_jsonb` existir, inclui-a no SELECT para que os
    services possam preferí-la sem casting extra.
    """
    with db_connect() as conn:
        cols = get_table_columns(conn, 'resultados')
        has_jsonb = 'posicoes_jsonb' in cols
        has_abandono_arr = 'abandono_arr' in cols

        extra = ''
        if has_jsonb:
            extra += ', posicoes_jsonb'
        if has_abandono_arr:
            extra += ', abandono_arr'

        if temporada:
            return pd.read_sql(
                f"SELECT prova_id, posicoes, abandono_pilotos{extra} FROM resultados "
                "JOIN provas ON resultados.prova_id = provas.id "
                "WHERE provas.temporada = %s",
                conn,
                params=(temporada,),
            )
        return pd.read_sql(
            f"SELECT prova_id, posicoes, abandono_pilotos{extra} FROM resultados",
            conn,
        )


# ---------------------------------------------------------------------------
# Race / schedule helpers
# ---------------------------------------------------------------------------

def get_horario_prova(prova_id: int) -> tuple[Optional[str], Optional[str], Optional[str]]:
    """Retorna (nome_prova, data, horario_prova) ou (None, None, None)."""
    with db_connect() as conn:
        cur = conn.cursor()
        cur.execute(
            "SELECT nome, data, horario_prova FROM provas WHERE id = %s",
            (prova_id,),
        )
        row = cur.fetchone()
    if row:
        return row["nome"], row["data"], row["horario_prova"]
    return None, None, None


# ---------------------------------------------------------------------------
# Aposta log helpers
# ---------------------------------------------------------------------------

def registrar_log_aposta(
    usuario_id: int,
    prova_id: int,
    apostador: str,
    pilotos: str,
    aposta: str,
    nome_prova: str,
    piloto_11: str,
    tipo_aposta: int,
    automatica: int,
    horario,
    ip_address: Optional[str] = None,
    temporada: Optional[str] = None,
    status: str = "Registrada",
) -> None:
    try:
        with db_connect() as conn:
            cur = conn.cursor()
            cols = get_table_columns(conn, "log_apostas")
            if not cols:
                return
            cur.execute(
                """
                INSERT INTO log_apostas
                    (usuario_id, prova_id, apostador, aposta, nome_prova,
                     pilotos, piloto_11, tipo_aposta, automatica, horario,
                     ip_address, temporada, status)
                VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
                """,
                (
                    usuario_id, prova_id, apostador, aposta, nome_prova,
                    pilotos, piloto_11, tipo_aposta, automatica, horario,
                    ip_address, temporada, status,
                ),
            )
            conn.commit()
    except Exception as exc:
        logger.debug("registrar_log_aposta falhou: %s", exc)


def log_aposta_existe(usuario_id: int, prova_id: int, temporada: Optional[str] = None) -> bool:
    with db_connect() as conn:
        cur = conn.cursor()
        if temporada:
            cur.execute(
                "SELECT 1 FROM log_apostas WHERE usuario_id=%s AND prova_id=%s AND temporada=%s LIMIT 1",
                (usuario_id, prova_id, temporada),
            )
        else:
            cur.execute(
                "SELECT 1 FROM log_apostas WHERE usuario_id=%s AND prova_id=%s LIMIT 1",
                (usuario_id, prova_id),
            )
        return cur.fetchone() is not None
