# Este arquivo é gerenciado pelo projeto BF1Homol.
# NÃO EDITE MANUALMENTE ESTE CABEÇALHO.
#
# Nota sobre função `table_exists`:
#   Adicionada para suporte às migrations. Já estava presente no
#   módulo; esta versão garante export explícito.

from __future__ import annotations

import logging
import threading
from contextlib import contextmanager
from datetime import datetime
from typing import Optional

import bcrypt
import pandas as pd

from db.connection_pool import get_pool

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Cache simples thread-safe (TTL em segundos)
# ---------------------------------------------------------------------------
_cache_lock = threading.Lock()
_cache: dict = {}


def _cache_get(key: str) -> Optional[object]:
    with _cache_lock:
        entry = _cache.get(key)
        if entry is None:
            return None
        value, expires_at = entry
        if datetime.now().timestamp() > expires_at:
            del _cache[key]
            return None
        return value


def _cache_set(key: str, value: object, ttl: int = 30) -> None:
    with _cache_lock:
        _cache[key] = (value, datetime.now().timestamp() + ttl)


def _cache_invalidate(prefix: str = "") -> None:
    with _cache_lock:
        keys = [k for k in _cache if k.startswith(prefix)]
        for k in keys:
            del _cache[k]


# ---------------------------------------------------------------------------
# Conexão
# ---------------------------------------------------------------------------

@contextmanager
def db_connect():
    pool = get_pool()
    with pool.get_connection() as conn:
        yield conn


# ---------------------------------------------------------------------------
# Helper interno: query -> DataFrame
# Substitui pd.read_sql que é incompatível com psycopg3 (dict_row).
# Todos os DataFrame helpers devem usar esta função.
# ---------------------------------------------------------------------------

def _query_to_df(query: str, params: tuple | None = None) -> pd.DataFrame:
    """Executa query via cursor psycopg3 e retorna DataFrame.

    pd.read_sql é incompatível com psycopg3 quando row_factory=dict_row:
    o pandas itera as chaves do dict em vez dos valores, resultando em
    células com o nome da coluna repetido em cada linha.
    """
    with db_connect() as conn:
        cur = conn.cursor()
        cur.execute(query, params or ())
        rows = cur.fetchall() or []
    if not rows:
        return pd.DataFrame()
    return pd.DataFrame([dict(r) for r in rows])


# ---------------------------------------------------------------------------
# Schema helpers
# ---------------------------------------------------------------------------

def get_table_columns(conn, table_name: str) -> list[str]:
    """Retorna lista de nomes de colunas de uma tabela."""
    cur = conn.cursor()
    cur.execute(
        """
        SELECT column_name
        FROM information_schema.columns
        WHERE table_name = %s
        ORDER BY ordinal_position
        """,
        (table_name,),
    )
    return [row["column_name"] for row in cur.fetchall()]


def table_exists(conn, table_name: str) -> bool:
    """Verifica se uma tabela existe no schema público."""
    cur = conn.cursor()
    cur.execute(
        """
        SELECT 1
        FROM information_schema.tables
        WHERE table_schema = 'public'
          AND table_name = %s
        LIMIT 1
        """,
        (table_name,),
    )
    return cur.fetchone() is not None


# ---------------------------------------------------------------------------
# Init DB (cria tabelas base)
# ---------------------------------------------------------------------------

def init_db() -> None:
    """Cria tabelas base se ainda não existirem."""
    ddl = """
        CREATE TABLE IF NOT EXISTS usuarios (
            id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            nome        TEXT NOT NULL,
            email       TEXT UNIQUE NOT NULL,
            senha       TEXT NOT NULL,
            perfil      TEXT DEFAULT 'participante',
            status      TEXT DEFAULT 'ativo',
            criado_em   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );

        CREATE TABLE IF NOT EXISTS pilotos (
            id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            nome    TEXT UNIQUE NOT NULL,
            equipe  TEXT DEFAULT '',
            status  TEXT DEFAULT 'Ativo',
            numero  INTEGER DEFAULT 0
        );

        CREATE TABLE IF NOT EXISTS provas (
            id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            nome            TEXT NOT NULL,
            data            TEXT,
            horario_prova   TEXT DEFAULT '',
            tipo            TEXT DEFAULT 'Normal',
            status          TEXT DEFAULT 'Pendente',
            temporada       TEXT
        );

        CREATE TABLE IF NOT EXISTS apostas (
            id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            usuario_id  INTEGER NOT NULL REFERENCES usuarios(id),
            prova_id    INTEGER NOT NULL REFERENCES provas(id),
            data_envio  TEXT,
            pilotos     TEXT,
            fichas      TEXT,
            piloto_11   TEXT,
            nome_prova  TEXT,
            automatica  INTEGER DEFAULT 0,
            temporada   TEXT
        );

        CREATE TABLE IF NOT EXISTS resultados (
            prova_id    INTEGER PRIMARY KEY REFERENCES provas(id),
            posicoes    TEXT
        );

        CREATE TABLE IF NOT EXISTS posicoes_participantes (
            id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            prova_id    INTEGER NOT NULL REFERENCES provas(id),
            usuario_id  INTEGER NOT NULL REFERENCES usuarios(id),
            posicao     INTEGER,
            pontos      REAL,
            temporada   TEXT
        );

        CREATE TABLE IF NOT EXISTS regras (
            id                      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            temporada               TEXT NOT NULL,
            tipo_prova              TEXT NOT NULL DEFAULT 'Normal',
            qtd_minima_pilotos      INTEGER DEFAULT 3,
            quantidade_fichas       INTEGER DEFAULT 15,
            fichas_por_piloto       INTEGER DEFAULT 15,
            mesma_equipe            BOOLEAN DEFAULT FALSE,
            pontos_11_colocado      INTEGER DEFAULT 25,
            penalidade_abandono     BOOLEAN DEFAULT FALSE,
            pontos_penalidade       INTEGER DEFAULT 0,
            pontos_dobrada          BOOLEAN DEFAULT FALSE,
            pontos_posicoes         TEXT,
            pontos_sprint_posicoes  TEXT,
            UNIQUE(temporada, tipo_prova)
        );
    """
    with db_connect() as conn:
        cur = conn.cursor()
        cur.execute(ddl)
        conn.commit()
    logger.info("✓ init_db concluído")


# ---------------------------------------------------------------------------
# Password helpers
# ---------------------------------------------------------------------------

def hash_password(plain: str) -> str:
    return bcrypt.hashpw(plain.encode(), bcrypt.gensalt()).decode()


def check_password(plain: str, hashed: str) -> bool:
    try:
        return bcrypt.checkpw(plain.encode(), hashed.encode())
    except Exception:
        return False


# ---------------------------------------------------------------------------
# User helpers
# ---------------------------------------------------------------------------

def get_user_by_email(email: str) -> Optional[dict]:
    with db_connect() as conn:
        cur = conn.cursor()
        cur.execute("SELECT * FROM usuarios WHERE email = %s", (email,))
        row = cur.fetchone()
        return dict(row) if row else None


def get_user_by_id(user_id: int) -> Optional[dict]:
    with db_connect() as conn:
        cur = conn.cursor()
        cur.execute("SELECT * FROM usuarios WHERE id = %s", (user_id,))
        row = cur.fetchone()
        return dict(row) if row else None


def get_master_user() -> Optional[dict]:
    with db_connect() as conn:
        cur = conn.cursor()
        cur.execute("SELECT * FROM usuarios WHERE perfil = 'master' LIMIT 1")
        row = cur.fetchone()
        return dict(row) if row else None


def cadastrar_usuario(nome: str, email: str, senha: str, perfil: str = "participante") -> bool:
    try:
        hashed = hash_password(senha)
        with db_connect() as conn:
            cur = conn.cursor()
            cur.execute(
                "INSERT INTO usuarios (nome, email, senha, perfil) VALUES (%s, %s, %s, %s)",
                (nome, email, hashed, perfil),
            )
            conn.commit()
        return True
    except Exception as exc:
        logger.warning("cadastrar_usuario falhou: %s", exc)
        return False


def autenticar_usuario(email: str, senha: str) -> Optional[dict]:
    user = get_user_by_email(email)
    if user and check_password(senha, user["senha"]):
        return user
    return None


# ---------------------------------------------------------------------------
# DataFrame helpers  (todos via _query_to_df — nunca pd.read_sql)
# ---------------------------------------------------------------------------

def get_usuarios_df() -> pd.DataFrame:
    return _query_to_df("SELECT * FROM usuarios")


def get_pilotos_df() -> pd.DataFrame:
    return _query_to_df("SELECT * FROM pilotos ORDER BY nome")


def get_provas_df(temporada: Optional[str] = None) -> pd.DataFrame:
    if temporada:
        return _query_to_df(
            "SELECT * FROM provas WHERE temporada = %s ORDER BY id",
            (temporada,),
        )
    return _query_to_df("SELECT * FROM provas ORDER BY id")


def get_apostas_df(temporada: Optional[str] = None) -> pd.DataFrame:
    if temporada:
        return _query_to_df(
            "SELECT * FROM apostas WHERE temporada = %s",
            (temporada,),
        )
    return _query_to_df("SELECT * FROM apostas")


def get_resultados_df(temporada: Optional[str] = None) -> pd.DataFrame:
    """
    Retorna DataFrame de resultados.
    Inclui posicoes_jsonb e abandono_arr quando existirem na tabela.
    """
    with db_connect() as conn:
        cols = get_table_columns(conn, "resultados")

    has_jsonb = "posicoes_jsonb" in cols
    has_abandono_arr = "abandono_arr" in cols

    extra = ""
    if has_jsonb:
        extra += ", posicoes_jsonb"
    if has_abandono_arr:
        extra += ", abandono_arr"

    if temporada:
        return _query_to_df(
            f"SELECT prova_id, posicoes, abandono_pilotos{extra} "
            "FROM resultados "
            "JOIN provas ON resultados.prova_id = provas.id "
            "WHERE provas.temporada = %s",
            (temporada,),
        )
    return _query_to_df(
        f"SELECT prova_id, posicoes, abandono_pilotos{extra} FROM resultados"
    )


# ---------------------------------------------------------------------------
# Race / schedule helpers
# ---------------------------------------------------------------------------

def get_horario_prova(prova_id: int) -> tuple[Optional[str], Optional[str], Optional[str]]:
    """Retorna (nome_prova, data, horario_prova) ou (None, None, None)."""
    with db_connect() as conn:
        cur = conn.cursor()
        cur.execute(
            "SELECT nome, data, horario_prova FROM provas WHERE id = %s",
            (prova_id,),
        )
        row = cur.fetchone()
    if row:
        return row["nome"], row["data"], row["horario_prova"]
    return None, None, None


# ---------------------------------------------------------------------------
# Aposta log helpers
# ---------------------------------------------------------------------------

def registrar_log_aposta(
    usuario_id: int,
    prova_id: int,
    apostador: str,
    pilotos: str,
    aposta: str,
    nome_prova: str,
    piloto_11: str,
    tipo_aposta: int,
    automatica: int,
    horario,
    ip_address: Optional[str] = None,
    temporada: Optional[str] = None,
    status: str = "Registrada",
) -> None:
    try:
        with db_connect() as conn:
            cur = conn.cursor()
            cols = get_table_columns(conn, "log_apostas")
            if not cols:
                return
            cur.execute(
                """
                INSERT INTO log_apostas
                    (usuario_id, prova_id, apostador, aposta, nome_prova,
                     pilotos, piloto_11, tipo_aposta, automatica, horario,
                     ip_address, temporada, status)
                VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
                """,
                (
                    usuario_id, prova_id, apostador, aposta, nome_prova,
                    pilotos, piloto_11, tipo_aposta, automatica, horario,
                    ip_address, temporada, status,
                ),
            )
            conn.commit()
    except Exception as exc:
        logger.debug("registrar_log_aposta falhou: %s", exc)


def log_aposta_existe(usuario_id: int, prova_id: int, temporada: Optional[str] = None) -> bool:
    with db_connect() as conn:
        cur = conn.cursor()
        if temporada:
            cur.execute(
                "SELECT 1 FROM log_apostas WHERE usuario_id=%s AND prova_id=%s AND temporada=%s LIMIT 1",
                (usuario_id, prova_id, temporada),
            )
        else:
            cur.execute(
                "SELECT 1 FROM log_apostas WHERE usuario_id=%s AND prova_id=%s LIMIT 1",
                (usuario_id, prova_id),
            )
        return cur.fetchone() is not None


# ---------------------------------------------------------------------------
# Histórico de status de usuários
# ---------------------------------------------------------------------------

def _usuarios_status_historico_exists(conn) -> bool:
    """Verifica se a tabela usuarios_status_historico existe."""
    return table_exists(conn, "usuarios_status_historico")


def usuarios_status_historico_disponivel() -> bool:
    """Indica se há histórico de status de usuários para filtros sazonais confiáveis."""
    with db_connect() as conn:
        return _usuarios_status_historico_exists(conn)


def registrar_historico_status_usuario(
    usuario_id: int,
    novo_status: str,
    alterado_por: Optional[int] = None,
    motivo: Optional[str] = None,
    data_referencia: Optional[str] = None,
) -> None:
    """Registra alteração de status do usuário no histórico.

    Fecha o período anterior e abre um novo registro com o status informado.
    """
    if data_referencia is None:
        data_referencia = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    with db_connect() as conn:
        cursor = conn.cursor()
        if not _usuarios_status_historico_exists(conn):
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS usuarios_status_historico (
                    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    usuario_id  INTEGER NOT NULL,
                    status      TEXT NOT NULL,
                    inicio_em   TIMESTAMP NOT NULL,
                    fim_em      TIMESTAMP,
                    alterado_por INTEGER,
                    motivo      TEXT,
                    FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
                )
            """)

        cursor.execute(
            "SELECT id, status FROM usuarios_status_historico "
            "WHERE usuario_id = %s AND fim_em IS NULL ORDER BY inicio_em DESC LIMIT 1",
            (usuario_id,),
        )
        row = cursor.fetchone()
        if row and row["status"] == novo_status:
            return

        if row:
            cursor.execute(
                "UPDATE usuarios_status_historico SET fim_em = %s WHERE id = %s",
                (data_referencia, row["id"]),
            )

        cursor.execute(
            """
            INSERT INTO usuarios_status_historico
                (usuario_id, status, inicio_em, fim_em, alterado_por, motivo)
            VALUES (%s, %s, %s, NULL, %s, %s)
            """,
            (usuario_id, novo_status, data_referencia, alterado_por, motivo),
        )
        conn.commit()


def get_participantes_temporada_df(temporada: Optional[str] = None) -> pd.DataFrame:
    """Retorna participantes ativos na temporada selecionada.

    Usa histórico de status quando disponível; caso contrário, usa status atual.
    """
    if temporada is None:
        temporada = str(datetime.now().year)
    season_start = f"{temporada}-01-01 00:00:00"
    season_end = f"{temporada}-12-31 23:59:59"

    with db_connect() as conn:
        has_hist = _usuarios_status_historico_exists(conn)

        if not has_hist:
            return _query_to_df("SELECT * FROM usuarios WHERE lower(trim(coalesce(status,''))) = 'ativo'")

        cur = conn.cursor()
        cur.execute("SELECT COUNT(*) AS cnt FROM usuarios_status_historico")
        row = cur.fetchone()
        if not row or int(row["cnt"]) == 0:
            return _query_to_df("SELECT * FROM usuarios WHERE lower(trim(coalesce(status,''))) = 'ativo'")

    df = _query_to_df(
        """
        SELECT DISTINCT u.*
        FROM usuarios u
        JOIN usuarios_status_historico h ON h.usuario_id = u.id
        WHERE lower(trim(coalesce(h.status,''))) = 'ativo'
          AND h.inicio_em <= %s
          AND (h.fim_em IS NULL OR h.fim_em >= %s)
        """,
        (season_end, season_start),
    )
    if not df.empty:
        return df
    return _query_to_df("SELECT * FROM usuarios WHERE lower(trim(coalesce(status,''))) = 'ativo'")


def get_usuario_temporadas_ativas(user_id: int) -> list[str]:
    """Retorna temporadas em que o usuário esteve com status ativo.

    Usa histórico de status quando disponível. Sem histórico:
    - usuário ativo  → retorna todas as temporadas existentes em provas
    - usuário inativo → infere temporadas via atividade registrada
    """

    def _infer_por_atividade(user_id: int) -> list[str]:
        """Coleta temporadas via apostas, log e posições do usuário."""
        temporadas: set[str] = set()

        # Apostas
        df = _query_to_df(
            "SELECT DISTINCT trim(coalesce(temporada,'')) AS t FROM apostas "
            "WHERE usuario_id = %s AND trim(coalesce(temporada,'')) <> ''",
            (int(user_id),),
        )
        temporadas.update(df["t"].tolist() if not df.empty else [])

        # Log de apostas
        with db_connect() as conn:
            log_cols = set(get_table_columns(conn, "log_apostas")) if table_exists(conn, "log_apostas") else set()
        user_col = "usuario_id" if "usuario_id" in log_cols else ("user_id" if "user_id" in log_cols else None)
        if user_col:
            parts = []
            if "temporada" in log_cols:
                parts.append("NULLIF(trim(coalesce(temporada,'')),'')")  
            if "data" in log_cols:
                parts.append("NULLIF(trim(substr(coalesce(data,''),1,4)),'')")  
            if parts:
                df2 = _query_to_df(
                    f"SELECT DISTINCT COALESCE({', '.join(parts)}) AS t "
                    f"FROM log_apostas WHERE {user_col} = %s",
                    (int(user_id),),
                )
                temporadas.update([v for v in df2["t"].tolist() if v] if not df2.empty else [])

        # Posições históricas
        with db_connect() as conn:
            has_pos = table_exists(conn, "posicoes_participantes")
        if has_pos:
            df3 = _query_to_df(
                "SELECT DISTINCT trim(coalesce(temporada,'')) AS t "
                "FROM posicoes_participantes "
                "WHERE usuario_id = %s AND trim(coalesce(temporada,'')) <> ''",
                (int(user_id),),
            )
            temporadas.update(df3["t"].tolist() if not df3.empty else [])

        return sorted(temporadas)

    # Todas as temporadas existentes em provas
    df_base = _query_to_df(
        """
        SELECT DISTINCT COALESCE(NULLIF(trim(temporada),''), substr(data,1,4)) AS t
        FROM provas
        WHERE COALESCE(NULLIF(trim(temporada),''), substr(data,1,4)) IS NOT NULL
        ORDER BY t
        """
    )
    temporadas_base = [str(v).strip() for v in df_base["t"].tolist() if v] if not df_base.empty else []
    if not temporadas_base:
        return []

    with db_connect() as conn:
        has_hist = _usuarios_status_historico_exists(conn)

    if not has_hist:
        # Sem histórico: usa status atual
        user = get_user_by_id(int(user_id))
        status = str(user.get("status", "")).strip().lower() if user else ""
        if status == "ativo":
            return temporadas_base
        return _infer_por_atividade(int(user_id))

    # Com histórico: filtra temporadas em que o usuário estava ativo
    df_ativas = _query_to_df(
        """
        SELECT DISTINCT s.t
        FROM (
            SELECT COALESCE(NULLIF(trim(temporada),''), substr(data,1,4)) AS t
            FROM provas
        ) s
        JOIN usuarios_status_historico h ON h.usuario_id = %s
        WHERE lower(trim(coalesce(h.status,''))) = 'ativo'
          AND h.inicio_em <= (s.t || '-12-31 23:59:59')::timestamp
          AND (h.fim_em IS NULL OR h.fim_em >= (s.t || '-01-01 00:00:00')::timestamp)
        ORDER BY s.t
        """,
        (int(user_id),),
    )
    if not df_ativas.empty:
        return [str(v).strip() for v in df_ativas["t"].tolist() if v]

    # Fallback: sem match no histórico, usa atividade registrada
    return _infer_por_atividade(int(user_id))
