"""Catálogo V4 de equipes, compatível com o nome legado em ``pilotos.equipe``."""
from __future__ import annotations

from db.db_schema import db_connect
from utils.cache_utils import clear_data_cache

DEFAULT_TEAM_COLORS: dict[str, tuple[str, str | None]] = {
    "Ferrari": ("#DC0000", None), "McLaren": ("#FF8700", None),
    "Red Bull Racing": ("#0A1B40", None), "Mercedes": ("#00A39A", None),
    "Aston Martin": ("#005F41", None), "Alpine": ("#005BA9", "#FF80BD"),
    "Williams": ("#1868DB", None), "RB (VCARB)": ("#6C98FF", None),
    "Kick Sauber": ("#01C00E", None), "Haas": ("#9C9FA2", "#EB0A1E"),
}


def ensure_equipes_table() -> None:
    """Cria e hidrata o catálogo sem alterar a tabela legada ``pilotos``."""
    with db_connect() as conn:
        cur = conn.cursor()
        cur.execute("""CREATE TABLE IF NOT EXISTS equipes (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            nome TEXT NOT NULL UNIQUE,
            cor_primaria TEXT NOT NULL DEFAULT '#687284',
            cor_secundaria TEXT,
            status TEXT NOT NULL DEFAULT 'Ativa',
            criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )""")
        cur.execute("CREATE UNIQUE INDEX IF NOT EXISTS idx_equipes_nome_norm ON equipes ((lower(trim(nome))))")
        cur.execute("SELECT DISTINCT trim(equipe) AS nome FROM pilotos WHERE trim(coalesce(equipe, '')) <> ''")
        for row in cur.fetchall() or []:
            name = str(row["nome"])
            primary, secondary = DEFAULT_TEAM_COLORS.get(name, ("#687284", None))
            cur.execute(
                """INSERT INTO equipes (nome,cor_primaria,cor_secundaria,status)
                   VALUES (%s,%s,%s,'Ativa') ON CONFLICT DO NOTHING""",
                (name, primary, secondary),
            )
        conn.commit()
        cur.close()


def list_equipes() -> list[dict]:
    ensure_equipes_table()
    with db_connect() as conn:
        cur = conn.cursor()
        cur.execute("SELECT id,nome,cor_primaria,cor_secundaria,status FROM equipes ORDER BY nome")
        rows = [dict(row) for row in (cur.fetchall() or [])]
        cur.close()
    return rows


def team_name_exists(name: str) -> bool:
    ensure_equipes_table()
    with db_connect() as conn:
        cur = conn.cursor()
        cur.execute("SELECT 1 FROM equipes WHERE lower(trim(nome))=lower(trim(%s)) LIMIT 1", (name,))
        exists = cur.fetchone() is not None
        cur.close()
    return exists


def save_equipe(team_id: int | None, *, name: str, primary_color: str, secondary_color: str | None, status: str) -> int:
    ensure_equipes_table()
    with db_connect() as conn:
        cur = conn.cursor()
        if team_id is None:
            cur.execute("SELECT 1 FROM equipes WHERE lower(trim(nome))=lower(trim(%s)) LIMIT 1", (name,))
            if cur.fetchone() is not None:
                raise ValueError("Já existe uma equipe com este nome.")
            cur.execute(
                """INSERT INTO equipes (nome,cor_primaria,cor_secundaria,status)
                   VALUES (%s,%s,%s,%s) RETURNING id""",
                (name, primary_color, secondary_color, status),
            )
            saved_id = int(cur.fetchone()["id"])
        else:
            cur.execute("SELECT 1 FROM equipes WHERE lower(trim(nome))=lower(trim(%s)) AND id<>%s LIMIT 1", (name, int(team_id)))
            if cur.fetchone() is not None:
                raise ValueError("Já existe uma equipe com este nome.")
            cur.execute("SELECT nome FROM equipes WHERE id=%s FOR UPDATE", (int(team_id),))
            current = cur.fetchone()
            if not current:
                raise ValueError("Equipe não encontrada.")
            old_name = str(current["nome"])
            cur.execute(
                """UPDATE equipes SET nome=%s,cor_primaria=%s,cor_secundaria=%s,
                   status=%s,atualizado_em=CURRENT_TIMESTAMP WHERE id=%s""",
                (name, primary_color, secondary_color, status, int(team_id)),
            )
            if old_name != name:
                cur.execute("UPDATE pilotos SET equipe=%s WHERE equipe=%s", (name, old_name))
            saved_id = int(team_id)
        conn.commit()
        cur.close()
    clear_data_cache("pilotos", "equipes")
    return saved_id


__all__ = ["ensure_equipes_table", "list_equipes", "save_equipe", "team_name_exists"]
