"""
Utilitários para Gestão de Regras de Temporada
"""

import logging
import json
from typing import Optional
from db.connection_pool import get_pool

logger = logging.getLogger(__name__)

def init_rules_table():
    """Cria a tabela de regras se não existir"""
    with get_pool().get_connection() as conn:
        c = conn.cursor()
        c.execute('''
            CREATE TABLE IF NOT EXISTS regras (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                nome_regra TEXT NOT NULL UNIQUE,
                
                -- Parâmetros de Apostas (12, 13, 14, 15)
                quantidade_fichas INTEGER NOT NULL DEFAULT 15,
                fichas_por_piloto INTEGER NOT NULL DEFAULT 15,
                mesma_equipe INTEGER NOT NULL DEFAULT 0,
                descarte INTEGER NOT NULL DEFAULT 0,
                
                -- Pontuações Fixas (2, 3, 4)
                pontos_pole INTEGER NOT NULL DEFAULT 0,
                pontos_vr INTEGER NOT NULL DEFAULT 0,
                pontos_posicoes TEXT DEFAULT '[25, 18, 15, 12, 10, 8, 6, 4, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]',
                pontos_11_colocado INTEGER NOT NULL DEFAULT 25,
                
                -- Regras Sprint (5, 6, 7)
                regra_sprint INTEGER NOT NULL DEFAULT 0,
                pontos_sprint_pole INTEGER NOT NULL DEFAULT 0,
                pontos_sprint_vr INTEGER NOT NULL DEFAULT 0,
                pontos_sprint_posicoes TEXT DEFAULT '[8, 7, 6, 5, 4, 3, 2, 1]',
                
                -- Bônus e Extras (8, 9, 10, 11)
                pontos_dobrada INTEGER NOT NULL DEFAULT 0, -- Corrida Final
                bonus_vencedor INTEGER NOT NULL DEFAULT 0,
                bonus_podio_completo INTEGER NOT NULL DEFAULT 0,
                bonus_podio_qualquer INTEGER NOT NULL DEFAULT 0,
                
                -- Outros (Legado/Suporte)
                qtd_minima_pilotos INTEGER NOT NULL DEFAULT 3,
                penalidade_abandono INTEGER NOT NULL DEFAULT 0,
                pontos_penalidade INTEGER DEFAULT 0,
                penalidade_auto_percent INTEGER NOT NULL DEFAULT 20,
                pontos_campeao INTEGER NOT NULL DEFAULT 150,
                pontos_vice INTEGER NOT NULL DEFAULT 100,
                pontos_equipe INTEGER NOT NULL DEFAULT 100
            )
        ''')
        
        c.execute('''
            CREATE TABLE IF NOT EXISTS temporadas_regras (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                regra_id INTEGER NOT NULL REFERENCES regras(id) ON DELETE CASCADE,
                temporada INTEGER NOT NULL,
                UNIQUE(temporada)
            )
        ''')
        conn.commit()
        logger.info("✓ Tabelas de regras inicializadas")

def salvar_regra(nome_regra: str, dados: dict) -> Optional[int]:
    """Salva uma nova regra e retorna o ID"""
    try:
        with get_pool().get_connection() as conn:
            c = conn.cursor()
            c.execute('''
                INSERT INTO regras (
                    nome_regra, quantidade_fichas, fichas_por_piloto, mesma_equipe,
                    descarte, pontos_pole, pontos_vr, pontos_posicoes,
                    pontos_11_colocado, regra_sprint, pontos_sprint_pole,
                    pontos_sprint_vr, pontos_sprint_posicoes, pontos_dobrada,
                    bonus_vencedor, bonus_podio_completo, bonus_podio_qualquer,
                    qtd_minima_pilotos, penalidade_abandono, pontos_penalidade,
                    penalidade_auto_percent, pontos_campeao, pontos_vice, pontos_equipe
                ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
                RETURNING id
            ''', (
                nome_regra,
                dados.get('quantidade_fichas', 15),
                dados.get('fichas_por_piloto', 15),
                1 if dados.get('mesma_equipe', False) else 0,
                1 if dados.get('descarte', False) else 0,
                dados.get('pontos_pole', 0),
                dados.get('pontos_vr', 0),
                json.dumps(dados.get('pontos_posicoes', [25, 18, 15, 12, 10, 8, 6, 4, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])),
                dados.get('pontos_11_colocado', 25),
                1 if dados.get('regra_sprint', False) else 0,
                dados.get('pontos_sprint_pole', 0),
                dados.get('pontos_sprint_vr', 0),
                json.dumps(dados.get('pontos_sprint_posicoes', [8, 7, 6, 5, 4, 3, 2, 1])),
                dados.get('pontos_dobrada', 0),
                dados.get('bonus_vencedor', 0),
                dados.get('bonus_podio_completo', 0),
                dados.get('bonus_podio_qualquer', 0),
                dados.get('qtd_minima_pilotos', 3),
                dados.get('penalidade_abandono', 0),
                dados.get('pontos_penalidade', 0),
                dados.get('penalidade_auto_percent', 20),
                dados.get('pontos_campeao', 150),
                dados.get('pontos_vice', 100),
                dados.get('pontos_equipe', 100)
            ))
            regra_id = c.fetchone()[0]
            conn.commit()
            logger.info("✓ Regra '%s' salva com ID %s", nome_regra, regra_id)
            return regra_id
    except Exception as e:
        logger.exception("Erro ao salvar regra: %s", e)
        return None

def atualizar_regra(regra_id: int, dados: dict) -> bool:
    """Atualiza uma regra existente"""
    try:
        with get_pool().get_connection() as conn:
            c = conn.cursor()
            c.execute('''
                UPDATE regras SET
                    nome_regra = %s,
                    quantidade_fichas = %s,
                    fichas_por_piloto = %s,
                    mesma_equipe = %s,
                    descarte = %s,
                    pontos_pole = %s,
                    pontos_vr = %s,
                    pontos_posicoes = %s,
                    pontos_11_colocado = %s,
                    regra_sprint = %s,
                    pontos_sprint_pole = %s,
                    pontos_sprint_vr = %s,
                    pontos_sprint_posicoes = %s,
                    pontos_dobrada = %s,
                    bonus_vencedor = %s,
                    bonus_podio_completo = %s,
                    bonus_podio_qualquer = %s,
                    qtd_minima_pilotos = %s,
                    penalidade_abandono = %s,
                    pontos_penalidade = %s,
                    penalidade_auto_percent = %s,
                    pontos_campeao = %s,
                    pontos_vice = %s,
                    pontos_equipe = %s
                WHERE id = %s
            ''', (
                dados['nome_regra'],
                dados.get('quantidade_fichas', 15),
                dados.get('fichas_por_piloto', 15),
                1 if dados.get('mesma_equipe', False) else 0,
                1 if dados.get('descarte', False) else 0,
                dados.get('pontos_pole', 0),
                dados.get('pontos_vr', 0),
                json.dumps(dados.get('pontos_posicoes', [25, 18, 15, 12, 10, 8, 6, 4, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])),
                dados.get('pontos_11_colocado', 25),
                1 if dados.get('regra_sprint', False) else 0,
                dados.get('pontos_sprint_pole', 0),
                dados.get('pontos_sprint_vr', 0),
                json.dumps(dados.get('pontos_sprint_posicoes', [8, 7, 6, 5, 4, 3, 2, 1])),
                dados.get('pontos_dobrada', 0),
                dados.get('bonus_vencedor', 0),
                dados.get('bonus_podio_completo', 0),
                dados.get('bonus_podio_qualquer', 0),
                dados.get('qtd_minima_pilotos', 3),
                dados.get('penalidade_abandono', 0),
                dados.get('pontos_penalidade', 0),
                dados.get('penalidade_auto_percent', 20),
                dados.get('pontos_campeao', 150),
                dados.get('pontos_vice', 100),
                dados.get('pontos_equipe', 100),
                regra_id
            ))
            conn.commit()
            logger.info("✓ Regra ID %s atualizada", regra_id)
            return True
    except Exception as e:
        logger.exception("Erro ao atualizar regra: %s", e)
        return False

def excluir_regra(regra_id: int) -> bool:
    """Exclui uma regra se não estiver vinculada a nenhuma temporada"""
    try:
        with get_pool().get_connection() as conn:
            c = conn.cursor()
            c.execute('SELECT COUNT(*) FROM temporadas_regras WHERE regra_id = %s', (regra_id,))
            vinculacoes = c.fetchone()[0]
            if vinculacoes > 0:
                return False
            c.execute('DELETE FROM regras WHERE id = %s', (regra_id,))
            conn.commit()
            logger.info("✓ Regra ID %s excluída", regra_id)
            return True
    except Exception as e:
        logger.exception("Erro ao excluir regra: %s", e)
        return False

def get_regra_por_id(regra_id: int) -> Optional[dict]:
    """Retorna uma regra pelo ID"""
    try:
        with get_pool().get_connection() as conn:
            c = conn.cursor()
            c.execute('SELECT * FROM regras WHERE id = %s', (regra_id,))
            row = c.fetchone()
            return dict(row) if row else None
    except Exception as e:
        logger.exception("Erro ao buscar regra por ID: %s", e)
        return None

def get_regra_por_nome(nome_regra: str) -> Optional[dict]:
    """Retorna uma regra pelo nome"""
    try:
        with get_pool().get_connection() as conn:
            c = conn.cursor()
            c.execute('SELECT * FROM regras WHERE nome_regra = %s', (nome_regra,))
            row = c.fetchone()
            return dict(row) if row else None
    except Exception as e:
        logger.exception("Erro ao buscar regra por nome: %s", e)
        return None

def get_temporadas_da_regra(regra_id: int) -> list[str]:
    """Retorna temporadas vinculadas a uma regra"""
    try:
        with get_pool().get_connection() as conn:
            c = conn.cursor()
            c.execute('SELECT temporada FROM temporadas_regras WHERE regra_id = %s', (regra_id,))
            rows = c.fetchall()
            return [str(r[0]) for r in rows] if rows else []
    except Exception as e:
        logger.exception("Erro ao buscar temporadas da regra: %s", e)
        return []

def clonar_regra(regra_id: int, novo_nome: str) -> Optional[int]:
    """Clona uma regra existente com novo nome"""
    regra = get_regra_por_id(regra_id)
    if not regra:
        return None
    regra.pop('id', None)
    regra['nome_regra'] = novo_nome
    return salvar_regra(novo_nome, regra)

def vincular_regra_temporada(regra_id: int, temporada: int) -> bool:
    """Vincula uma regra a uma temporada"""
    try:
        with get_pool().get_connection() as conn:
            c = conn.cursor()
            c.execute('''
                INSERT INTO temporadas_regras (regra_id, temporada)
                VALUES (%s, %s)
                ON CONFLICT (temporada) DO UPDATE SET
                    regra_id = EXCLUDED.regra_id
            ''', (regra_id, temporada))
            conn.commit()
            logger.info("✓ Regra %s vinculada à temporada %s", regra_id, temporada)
            return True
    except Exception as e:
        logger.exception("Erro ao vincular regra à temporada: %s", e)
        return False

def get_regras_df():
    """Retorna DataFrame com regras e temporadas vinculadas"""
    import pandas as pd
    try:
        with get_pool().get_connection() as conn:
            query = '''
            SELECT 
                r.id,
                r.nome_regra,
                r.quantidade_fichas,
                r.fichas_por_piloto,
                r.mesma_equipe,
                r.descarte,
                r.pontos_pole,
                r.pontos_vr,
                r.pontos_11_colocado,
                r.regra_sprint,
                r.pontos_sprint_pole,
                r.pontos_sprint_vr,
                r.pontos_dobrada,
                r.bonus_vencedor,
                r.bonus_podio_completo,
                r.bonus_podio_qualquer,
                r.qtd_minima_pilotos,
                r.penalidade_abandono,
                r.pontos_penalidade,
                r.penalidade_auto_percent,
                r.pontos_campeao,
                r.pontos_vice,
                r.pontos_equipe,
                tr.temporada
            FROM regras r
            LEFT JOIN temporadas_regras tr ON r.id = tr.regra_id
            ORDER BY r.nome_regra, tr.temporada
            '''
            return pd.read_sql_query(query, conn)
    except Exception as e:
        logger.exception("Erro ao buscar DataFrame de regras: %s", e)
        return pd.DataFrame()

def get_regra_da_temporada(temporada: int) -> Optional[dict]:
    """Retorna a regra vinculada a uma temporada"""
    try:
        with get_pool().get_connection() as conn:
            c = conn.cursor()
            c.execute('''
            SELECT r.*
            FROM regras r
            JOIN temporadas_regras tr ON r.id = tr.regra_id
            WHERE tr.temporada = %s
            ''', (temporada,))
            row = c.fetchone()
            return dict(row) if row else None
    except Exception as e:
        logger.exception("Erro ao buscar regra da temporada: %s", e)
        return None
