import streamlit as st
import pandas as pd
from db.db_utils import get_usuarios_df, db_connect, registrar_historico_status_usuario
from services.auth_service import hash_password
from db.db_utils import get_participantes_temporada_df, usuarios_status_historico_disponivel
from services.email_service import enviar_email
from datetime import datetime
from utils.helpers import render_page_header
from utils.season_utils import get_default_season_index, get_season_options


def _normalizar_df_usuarios(df: pd.DataFrame) -> pd.DataFrame:
    """Normaliza DataFrame de usuários para evitar quebras por dados inválidos."""
    if df.empty:
        return df

    df_norm = df.copy()

    if "id" in df_norm.columns:
        df_norm["id"] = pd.to_numeric(df_norm["id"], errors="coerce")
        df_norm = df_norm[df_norm["id"].notna()].copy()
        df_norm["id"] = df_norm["id"].astype(int)

    if "perfil" in df_norm.columns:
        df_norm["perfil"] = df_norm["perfil"].astype(str).str.strip().str.lower()

    if "status" in df_norm.columns:
        df_norm["status"] = df_norm["status"].astype(str).str.strip().str.title()

    if "faltas" in df_norm.columns:
        df_norm["faltas"] = pd.to_numeric(df_norm["faltas"], errors="coerce").fillna(0).astype(int)

    return df_norm


def _ensure_gestao_financeira_table() -> None:
    with db_connect() as conn:
        c = conn.cursor()
        c.execute('''
            CREATE TABLE IF NOT EXISTS financeiro_participantes (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                usuario_id INTEGER NOT NULL,
                temporada TEXT NOT NULL,
                pago INTEGER NOT NULL DEFAULT 0,
                atualizado_em TEXT DEFAULT CURRENT_TIMESTAMP,
                UNIQUE(usuario_id, temporada),
                FOREIGN KEY(usuario_id) REFERENCES usuarios(id)
            )
        ''')
        c.execute('''
            CREATE TABLE IF NOT EXISTS financeiro_config_temporada (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                temporada TEXT NOT NULL UNIQUE,
                valor_taxa REAL NOT NULL DEFAULT 0,
                atualizado_em TEXT DEFAULT CURRENT_TIMESTAMP
            )
        ''')
        conn.commit()


def _get_pagamentos_temporada(temporada: str) -> dict[int, bool]:
    _ensure_gestao_financeira_table()
    with db_connect() as conn:
        c = conn.cursor()
        c.execute(
            "SELECT usuario_id, pago FROM financeiro_participantes WHERE temporada = %s",
            (str(temporada),)
        )
        rows = c.fetchall()
    return {int(r['usuario_id']): bool(int(r['pago'])) for r in rows}


def _salvar_pagamentos_temporada(temporada: str, pagamentos: dict[int, bool]) -> None:
    _ensure_gestao_financeira_table()
    with db_connect() as conn:
        c = conn.cursor()
        for usuario_id, pago in pagamentos.items():
            c.execute(
                '''
                INSERT INTO financeiro_participantes (usuario_id, temporada, pago, atualizado_em)
                VALUES (%s, %s, %s, CURRENT_TIMESTAMP)
                ON CONFLICT(usuario_id, temporada)
                DO UPDATE SET pago = excluded.pago, atualizado_em = CURRENT_TIMESTAMP
                ''',
                (int(usuario_id), str(temporada), 1 if pago else 0)
            )
        conn.commit()


def _get_valor_taxa_temporada(temporada: str) -> float:
    _ensure_gestao_financeira_table()
    with db_connect() as conn:
        c = conn.cursor()
        c.execute(
            "SELECT valor_taxa FROM financeiro_config_temporada WHERE temporada = %s LIMIT 1",
            (str(temporada),),
        )
        row = c.fetchone()
    if not row:
        return 0.0
    try:
        return float(row['valor_taxa'])
    except Exception:
        return 0.0


def _salvar_valor_taxa_temporada(temporada: str, valor_taxa: float) -> None:
    _ensure_gestao_financeira_table()
    with db_connect() as conn:
        c = conn.cursor()
        c.execute(
            '''
            INSERT INTO financeiro_config_temporada (temporada, valor_taxa, atualizado_em)
            VALUES (%s, %s, CURRENT_TIMESTAMP)
            ON CONFLICT(temporada)
            DO UPDATE SET valor_taxa = excluded.valor_taxa, atualizado_em = CURRENT_TIMESTAMP
            ''',
            (str(temporada), float(valor_taxa)),
        )
        conn.commit()


def _fmt_brl(valor: float) -> str:
    try:
        return f"R$ {float(valor):,.2f}".replace(",", "v").replace(".", ",").replace("v", ".")
    except Exception:
        return "R$ 0,00"


def _render_gestao_usuarios_tab(perfil: str):
    df = _normalizar_df_usuarios(get_usuarios_df())
    if df.empty:
        st.info("Nenhum usuário cadastrado.")
        return

    st.markdown("### Usuários Cadastrados")
    with st.expander("Lista Completa de Usuários", expanded=True):
        # Colunas base sempre presentes
        base_cols = ["id", "nome", "email", "perfil", "status"]
        base_labels = ["ID", "Nome", "Email", "Perfil", "Status"]

        # Inclui 'faltas' de forma defensiva: só se a coluna existir no banco real.
        if "faltas" in df.columns:
            base_cols.append("faltas")
            base_labels.append("Faltas")

        show_df = df[base_cols].copy()
        show_df.columns = base_labels
        st.dataframe(show_df, width="stretch")

    st.markdown("### Editar Usuário")

    usuarios = df["nome"].tolist()
    selected = st.selectbox("Selecione um usuário para editar", usuarios)
    user_row = df[df["nome"] == selected].iloc[0]

    # Campos de edição
    novo_nome = st.text_input("Nome", user_row["nome"])
    novo_email = st.text_input("Email", user_row["email"])
    perfis = ["participante", "admin", "master"]
    perfil_atual = str(user_row.get("perfil", "participante")).strip().lower()
    perfil_index = perfis.index(perfil_atual) if perfil_atual in perfis else 0
    novo_perfil = st.selectbox("Perfil", perfis, index=perfil_index)

    status_opts = ["Ativo", "Inativo"]
    status_atual = str(user_row.get("status", "Ativo")).strip().title()
    status_index = status_opts.index(status_atual) if status_atual in status_opts else 0
    novo_status = st.selectbox("Status", status_opts, index=status_index)

    # fix: campo de edição de faltas — ausente antes, forçando workaround
    # de reimportar a tabela de usuários (o que quebrava as FK apostas.usuario_id).
    # Renderiza de forma defensiva: só se a coluna existir no DataFrame.
    novas_faltas = None
    if "faltas" in df.columns:
        faltas_atuais = int(user_row.get("faltas", 0) or 0)
        novas_faltas = st.number_input(
            "Faltas",
            min_value=0,
            value=faltas_atuais,
            step=1,
            help="Número de faltas do participante nesta temporada.",
        )

    col1, col2 = st.columns(2)

    with col1:
        if st.button("Atualizar usuário"):
            status_anterior = str(user_row["status"]).strip()
            with db_connect() as conn:
                c = conn.cursor()
                if novas_faltas is not None:
                    # Inclui faltas no UPDATE quando a coluna está disponível
                    c.execute(
                        "UPDATE usuarios SET nome=%s, email=%s, perfil=%s, status=%s, faltas=%s WHERE id=%s",
                        (novo_nome, novo_email, novo_perfil, novo_status, int(novas_faltas), int(user_row["id"]))
                    )
                else:
                    c.execute(
                        "UPDATE usuarios SET nome=%s, email=%s, perfil=%s, status=%s WHERE id=%s",
                        (novo_nome, novo_email, novo_perfil, novo_status, int(user_row["id"]))
                    )
                conn.commit()
            if status_anterior != novo_status:
                alterado_por = st.session_state.get("user_id")
                data_referencia_status = None
                if str(novo_status).strip().lower() == "inativo":
                    ano_anterior = datetime.now().year - 1
                    data_referencia_status = f"{ano_anterior}-12-31 23:59:59"
                registrar_historico_status_usuario(
                    int(user_row["id"]),
                    novo_status,
                    alterado_por=alterado_por,
                    motivo="gestao_usuarios",
                    data_referencia=data_referencia_status,
                )
            st.success("Usuário atualizado!")
            st.cache_data.clear()
            st.rerun()

    with col2:
        if "alterar_senha" not in st.session_state:
            st.session_state["alterar_senha"] = False

        if st.button("Alterar senha do usuário"):
            st.session_state["alterar_senha"] = True

        if st.session_state["alterar_senha"]:
            nova_senha = st.text_input("Nova senha", type="password", key="senha_reset")
            if st.button("Salvar nova senha"):
                if not nova_senha:
                    st.error("Digite a nova senha.")
                else:
                    nova_hash = hash_password(nova_senha)
                    with db_connect() as conn:
                        c = conn.cursor()
                        # fix: coluna correta é 'senha_hash' (DDL e banco de produção).
                        # Antes usava 'senha', que não existe — UPDATE não afetava nenhuma linha.
                        c.execute(
                            "UPDATE usuarios SET senha_hash=%s, must_change_password=TRUE WHERE id=%s",
                            (nova_hash, int(user_row["id"]))
                        )
                        conn.commit()
                    st.success("Senha atualizada com sucesso! O usuário deverá trocar a senha no próximo acesso.")
                    st.session_state["alterar_senha"] = False
                    st.rerun()
            if st.button("Cancelar alteração de senha"):
                st.session_state["alterar_senha"] = False

    st.markdown("### Excluir usuário")
    if perfil == "master":
        if st.button("Excluir usuário selecionado"):
            if user_row["perfil"] == "master":
                st.error("Não é possível excluir um usuário master.")
            else:
                with db_connect() as conn:
                    c = conn.cursor()
                    c.execute("DELETE FROM usuarios WHERE id=%s", (int(user_row["id"]),))
                    conn.commit()
                st.success("Usuário excluído com sucesso!")
                st.cache_data.clear()
                st.rerun()

    st.markdown("---")
    st.markdown("### Adicionar Novo Usuário")
    nome_novo = st.text_input("Nome completo", key="novo_nome")
    email_novo = st.text_input("Email", key="novo_email")
    senha_novo = st.text_input("Senha", type="password", key="nova_senha")
    perfil_novo = st.selectbox("Perfil", ["participante", "admin", "master"], key="novo_perfil")
    status_novo = st.selectbox("Status", ["Ativo", "Inativo"], key="novo_status")

    if st.button("Adicionar usuário"):
        if not nome_novo or not email_novo or not senha_novo:
            st.error("Preencha todos os campos obrigatórios.")
        else:
          from services.auth_service import cadastrar_usuario
          sucesso = cadastrar_usuario(nome_novo, email_novo, senha_novo, perfil=perfil_novo, status=status_novo)
          if sucesso:
              st.success("Usuário adicionado com sucesso!")
              st.cache_data.clear()
              st.rerun()
          else:
              st.error("Email já cadastrado.")


def _render_gestao_financeira_tab():
    st.subheader("Gestão financeira")

    if not usuarios_status_historico_disponivel():
        st.warning(
            "⚠️ Aviso técnico: a tabela de histórico de status de usuários não foi encontrada. "
            "Para temporadas anteriores, a lista pode refletir o status atual em vez do status histórico da temporada."
        )

    current_year = str(datetime.now().year)
    season_options = get_season_options()
    temporada = st.selectbox(
        "Temporada",
        season_options,
        index=get_default_season_index(season_options, current_year=current_year),
        key="usuarios_finance_temporada",
    )

    valor_taxa_atual = _get_valor_taxa_temporada(temporada)
    valor_taxa = st.number_input(
        "Valor da taxa",
        min_value=0.0,
        value=float(valor_taxa_atual),
        step=5.0,
        format="%.2f",
        key=f"finance_taxa_{temporada}",
    )
    if st.button("Salvar valor da taxa", key=f"finance_save_taxa_{temporada}"):
        _salvar_valor_taxa_temporada(temporada, valor_taxa)
        st.success("Valor da taxa salvo com sucesso!")

    participantes = get_participantes_temporada_df(temporada)
    if not participantes.empty and "perfil" in participantes.columns:
        participantes = participantes[
            participantes["perfil"].astype(str).str.strip().str.lower() != "master"
        ]
    participantes = participantes.sort_values("nome") if not participantes.empty else participantes

    if participantes.empty:
        st.info("Não há participantes ativos nesta temporada.")
        return

    pagamentos_db = _get_pagamentos_temporada(temporada)
    pagamentos_tela: dict[int, bool] = {}
    destinatarios_pendentes = []

    st.markdown("### Participantes ativos")
    mostrar_apenas_devendo = st.checkbox(
        "Mostrar apenas devendo",
        value=False,
        key=f"finance_show_only_pending_{temporada}",
    )

    for _, part in participantes.iterrows():
        try:
            usuario_id = int(str(part.get("id", "")).strip())
        except Exception:
            continue
        email = str(part.get("email", "") or "").strip()
        pago_default = bool(pagamentos_db.get(usuario_id, False))
        checkbox_key = f"finance_pago_{temporada}_{usuario_id}"
        if checkbox_key not in st.session_state:
            st.session_state[checkbox_key] = pago_default
        pago_atual = bool(st.session_state.get(checkbox_key, pago_default))

        if not (mostrar_apenas_devendo and pago_atual):
            st.checkbox(
                f"{part.get('nome', 'Participante')} ({email if email else 'sem e-mail'})",
                value=pago_atual,
                key=checkbox_key,
            )
            pago_atual = bool(st.session_state.get(checkbox_key, pago_atual))

        pagamentos_tela[usuario_id] = pago_atual
        if not pago_atual:
            destinatarios_pendentes.append({
                "Nome": str(part.get("nome", "Participante")),
                "E-mail": email,
            })

    total_ativos = len(participantes)
    total_pagos = sum(1 for v in pagamentos_tela.values() if v)
    total_devendo = total_ativos - total_pagos

    c1, c2, c3 = st.columns(3)
    c1.metric("Ativos na temporada", total_ativos)
    c2.metric("Pagaram", total_pagos)
    c3.metric("Devendo", total_devendo)

    total_arrecadado = total_pagos * float(valor_taxa)
    total_geral = total_ativos * float(valor_taxa)
    saldo_receber = total_geral - total_arrecadado
    premio_vencedor = total_geral * 0.40
    premio_vice = total_geral * 0.30
    premio_terceiro = total_geral * 0.20
    taxa_admin = total_geral * 0.10

    col_save, col_mail = st.columns(2)
    with col_save:
        if st.button("Salvar status de pagamento", key="finance_save"):
            _salvar_pagamentos_temporada(temporada, pagamentos_tela)
            st.success("Status financeiro salvo com sucesso!")

    st.markdown("### Resumo financeiro")
    r1, r2, r3 = st.columns(3)
    r1.metric("Total arrecadado (pagantes)", _fmt_brl(total_arrecadado))
    r2.metric("Saldo a receber", _fmt_brl(saldo_receber))
    r3.metric("Total geral", _fmt_brl(total_geral))

    resumo_premios = pd.DataFrame(
        [
            {"Destino": "1º colocado (40%)", "Valor": _fmt_brl(premio_vencedor)},
            {"Destino": "2º colocado (30%)", "Valor": _fmt_brl(premio_vice)},
            {"Destino": "3º colocado (20%)", "Valor": _fmt_brl(premio_terceiro)},
            {"Destino": "Taxa de administração (10%)", "Valor": _fmt_brl(taxa_admin)},
        ]
    )
    st.markdown("### Resumo dos prêmios")
    st.dataframe(resumo_premios, width="stretch", hide_index=True)

    pendentes_preview = [d for d in destinatarios_pendentes if d["E-mail"]]
    st.markdown("### Pendentes para lembrete")
    if destinatarios_pendentes:
        st.dataframe(destinatarios_pendentes, width="stretch", hide_index=True)
    else:
        st.info("Nenhum participante está devendo nesta temporada.")

    with col_mail:
        if st.button(
            "Enviar lembrete financeiro (CCO)",
            key="finance_email",
            disabled=not bool(pendentes_preview),
        ):
            assunto = f"Lembrete cordial - taxa da temporada {temporada}"
            corpo = (
                "<p>Olá, participante!</p>"
                f"<p>Este é um lembrete cordial sobre a taxa da temporada <b>{temporada}</b>.</p>"
                "<p>Se o pagamento já foi realizado recentemente, por favor desconsidere esta mensagem.</p>"
                "<p>Em caso de dúvida, entre em contato com a administração.</p>"
                "<p>Obrigado!</p>"
            )
            ok = enviar_email(
                destinatario="",
                assunto=assunto,
                corpo_html=corpo,
                cco=[d["E-mail"] for d in pendentes_preview],
            )
            if ok:
                st.success(f"Lembrete enviado em CCO para {len(pendentes_preview)} participante(s).")
            else:
                st.error("Falha ao enviar lembrete financeiro.")

def main():
    render_page_header(st, "Gestão de Usuários")

    # Definir permissões necessárias: apenas master pode editar tudo, admin pode ver; participante não acessa
    perfil = st.session_state.get("user_role", "participante")
    if perfil not in ("admin", "master"):
        st.warning("Acesso restrito a administradores.")
        return

    aba_usuarios, aba_financeira = st.tabs(["Gestão de Usuários", "Gestão financeira"])
    with aba_usuarios:
        _render_gestao_usuarios_tab(perfil)
    with aba_financeira:
        _render_gestao_financeira_tab()

if __name__ == "__main__":
    main()
