export const TRACK_ASSETS: Record<string, { src: string; source: string }> = {
  albert_park: { src: "/tracks/albert_park.svg", source: "julesr0y/f1-circuits-svg" },
  shanghai: { src: "/tracks/shanghai-1.svg", source: "julesr0y/f1-circuits-svg" },
  suzuka: { src: "/tracks/suzuka-2.svg", source: "julesr0y/f1-circuits-svg" },
  bahrain: { src: "/tracks/bahrain-1.svg", source: "julesr0y/f1-circuits-svg" },
  jeddah: { src: "/tracks/jeddah-1.svg", source: "julesr0y/f1-circuits-svg" },
  miami: { src: "/tracks/miami-1.svg", source: "julesr0y/f1-circuits-svg" },
  villeneuve: { src: "/tracks/villeneuve.svg", source: "julesr0y/f1-circuits-svg" },
  monaco: { src: "/tracks/monaco-6.svg", source: "julesr0y/f1-circuits-svg" },
  catalunya: { src: "/tracks/catalunya.svg", source: "julesr0y/f1-circuits-svg" },
  red_bull_ring: { src: "/tracks/red_bull_ring.svg", source: "julesr0y/f1-circuits-svg" },
  silverstone: { src: "/tracks/silverstone.svg", source: "julesr0y/f1-circuits-svg" },
  spa: { src: "/tracks/spa.svg", source: "julesr0y/f1-circuits-svg" },
  hungaroring: { src: "/tracks/hungaroring-3.svg", source: "julesr0y/f1-circuits-svg" },
  zandvoort: { src: "/tracks/zandvoort-5.svg", source: "julesr0y/f1-circuits-svg" },
  monza: { src: "/tracks/monza-7.svg", source: "julesr0y/f1-circuits-svg" },
  madring: { src: "/tracks/madring.svg", source: "julesr0y/f1-circuits-svg" },
  baku: { src: "/tracks/baku-1.svg", source: "julesr0y/f1-circuits-svg" },
  marina_bay: { src: "/tracks/marina_bay.svg", source: "julesr0y/f1-circuits-svg" },
  americas: { src: "/tracks/americas.svg", source: "julesr0y/f1-circuits-svg" },
  rodriguez: { src: "/tracks/rodriguez.svg", source: "julesr0y/f1-circuits-svg" },
  interlagos: { src: "/tracks/interlagos.svg", source: "julesr0y/f1-circuits-svg" },
  vegas: { src: "/tracks/vegas.svg", source: "julesr0y/f1-circuits-svg" },
  losail: { src: "/tracks/losail.svg", source: "julesr0y/f1-circuits-svg" },
  yas_marina: { src: "/tracks/yas_marina.svg", source: "julesr0y/f1-circuits-svg" },
};
